package cn.armylife.member.Mapper;

import cn.armylife.common.Domain.Alid;

import java.util.List;

public interface AlidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alid
     *
     * @mbggenerated
     */
    int insert(Alid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alid
     *
     * @mbggenerated
     */
    List<Alid> selectAll();

    /**
     * 查询授权码
     * @param alid
     * @return
     */
    Alid inspectShopForALID(String alid);
}