package cn.armylife.member.mapper;

        import cn.armylife.common.domain.MemberDeliveryaddress;

        import java.util.List;

public interface MemberDeliveryaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deliveryaddress
     *
     * @mbggenerated
     */
    int insert(MemberDeliveryaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deliveryaddress
     *
     * @mbggenerated
     */
    List<MemberDeliveryaddress> selectAll();

    /**
     * 删除收货地址
     * @param addressId
     * @return
     */
    int removeAddress(Long addressId);

    /**
     * 查询用户的收获地址
     * @param memberId
     * @return
     */
    List<MemberDeliveryaddress> searchAddress(Long memberId);

    /**
     * 修改地址
     * @param memberDeliveryaddress
     * @return
     */
    int updateAddress(MemberDeliveryaddress memberDeliveryaddress);
}