package cn.armylife.member.mapper;

import cn.armylife.common.domain.ProductDetail;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface ProductDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produvt_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produvt_detail
     *
     * @mbggenerated
     */
    int insert(ProductDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produvt_detail
     *
     * @mbggenerated
     */
    ProductDetail selectByPrimaryKey(Integer productDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produvt_detail
     *
     * @mbggenerated
     */
    List<ProductDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produvt_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDetail record);
}