package cn.armylife.common.mapper;

import cn.armylife.common.domain.Hairvip;
import java.util.List;

public interface HairvipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    int insert(Hairvip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    List<Hairvip> selectAll();
}