package cn.armylife.common.mapper;

import cn.armylife.common.domain.MemberDeliveryaddress;
import java.util.List;

public interface MemberDeliveryaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deliveryaddress
     *
     * @mbggenerated
     */
    int insert(MemberDeliveryaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deliveryaddress
     *
     * @mbggenerated
     */
    List<MemberDeliveryaddress> selectAll();
}