package cn.armylife.admin.service;

import cn.armylife.admin.domain.Admin;
import cn.armylife.admin.domain.Member;
import cn.armylife.admin.domain.ShopOrder;
import com.github.pagehelper.Page;

public interface AdminService {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    Page<Member> userSelectAll();

    /**
     * 查询用户总数
     * @return
     */
    Integer numberForUsers();

    /**
     *查询当日总收入
     * @param time
     * @return
     */
    Integer incomeToDay(String time);

    /**
     * 查询时间段人数
     * @param time
     * @return
     */
    Integer weekNumForUsers(String time);

    /**
     * 全部订单
     * @return
     */
    Page<ShopOrder> orderSelectAll();

    /**
     * 登录
     * @return
     */
    Admin loginAdmin(Admin admin);
}
