package cn.armylife.admin.domain;

import java.io.Serializable;
import java.util.Date;

public class MallArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_area.mall_area_id
     *
     * @mbggenerated
     */
    private Long mallAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_area.mall_area_name
     *
     * @mbggenerated
     */
    private String mallAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_area.adding_time
     *
     * @mbggenerated
     */
    private Date addingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_area
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_area.mall_area_id
     *
     * @return the value of mall_area.mall_area_id
     *
     * @mbggenerated
     */
    public Long getMallAreaId() {
        return mallAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_area.mall_area_id
     *
     * @param mallAreaId the value for mall_area.mall_area_id
     *
     * @mbggenerated
     */
    public void setMallAreaId(Long mallAreaId) {
        this.mallAreaId = mallAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_area.mall_area_name
     *
     * @return the value of mall_area.mall_area_name
     *
     * @mbggenerated
     */
    public String getMallAreaName() {
        return mallAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_area.mall_area_name
     *
     * @param mallAreaName the value for mall_area.mall_area_name
     *
     * @mbggenerated
     */
    public void setMallAreaName(String mallAreaName) {
        this.mallAreaName = mallAreaName == null ? null : mallAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_area.adding_time
     *
     * @return the value of mall_area.adding_time
     *
     * @mbggenerated
     */
    public Date getAddingTime() {
        return addingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_area.adding_time
     *
     * @param addingTime the value for mall_area.adding_time
     *
     * @mbggenerated
     */
    public void setAddingTime(Date addingTime) {
        this.addingTime = addingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_area
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mallAreaId=").append(mallAreaId);
        sb.append(", mallAreaName=").append(mallAreaName);
        sb.append(", addingTime=").append(addingTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}