package cn.armylife.admin.domain;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.userID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.userPwd
     *
     * @mbggenerated
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.masterID
     *
     * @mbggenerated
     */
    private Integer masterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.IDCardID
     *
     * @mbggenerated
     */
    private String idcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.memberAbility
     *
     * @mbggenerated
     */
    private Boolean memberability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.weChatNumber
     *
     * @mbggenerated
     */
    private String wechatnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.classLevel
     *
     * @mbggenerated
     */
    private Byte classlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.isActive
     *
     * @mbggenerated
     */
    private Boolean isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.recommendationCode
     *
     * @mbggenerated
     */
    private String recommendationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.cardSeriesNumber
     *
     * @mbggenerated
     */
    private Long cardseriesnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.lastLoginDatetime
     *
     * @mbggenerated
     */
    private Date lastlogindatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reward_person
     *
     * @mbggenerated
     */
    private Double rewardPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reward_master
     *
     * @mbggenerated
     */
    private Double rewardMaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reward_prentice
     *
     * @mbggenerated
     */
    private Double rewardPrentice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.starNum
     *
     * @mbggenerated
     */
    private Integer starnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.badReviewNum
     *
     * @mbggenerated
     */
    private Integer badreviewnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.registrationTime
     *
     * @mbggenerated
     */
    private Date registrationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.customerServiceID
     *
     * @mbggenerated
     */
    private Integer customerserviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ureward
     *
     * @mbggenerated
     */
    private Double ureward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.starLevel
     *
     * @mbggenerated
     */
    private String starlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.modificationTime
     *
     * @mbggenerated
     */
    private Date modificationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.informationTime
     *
     * @mbggenerated
     */
    private Date informationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.userKey
     *
     * @mbggenerated
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.remove
     *
     * @mbggenerated
     */
    private Integer remove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.removetime
     *
     * @mbggenerated
     */
    private String removetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.userID
     *
     * @return the value of member.userID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.userID
     *
     * @param userid the value for member.userID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.userName
     *
     * @return the value of member.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.userName
     *
     * @param username the value for member.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.openid
     *
     * @return the value of member.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.openid
     *
     * @param openid the value for member.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.userPwd
     *
     * @return the value of member.userPwd
     *
     * @mbggenerated
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.userPwd
     *
     * @param userpwd the value for member.userPwd
     *
     * @mbggenerated
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.masterID
     *
     * @return the value of member.masterID
     *
     * @mbggenerated
     */
    public Integer getMasterid() {
        return masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.masterID
     *
     * @param masterid the value for member.masterID
     *
     * @mbggenerated
     */
    public void setMasterid(Integer masterid) {
        this.masterid = masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.IDCardID
     *
     * @return the value of member.IDCardID
     *
     * @mbggenerated
     */
    public String getIdcardid() {
        return idcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.IDCardID
     *
     * @param idcardid the value for member.IDCardID
     *
     * @mbggenerated
     */
    public void setIdcardid(String idcardid) {
        this.idcardid = idcardid == null ? null : idcardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone
     *
     * @return the value of member.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone
     *
     * @param phone the value for member.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.memberAbility
     *
     * @return the value of member.memberAbility
     *
     * @mbggenerated
     */
    public Boolean getMemberability() {
        return memberability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.memberAbility
     *
     * @param memberability the value for member.memberAbility
     *
     * @mbggenerated
     */
    public void setMemberability(Boolean memberability) {
        this.memberability = memberability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.weChatNumber
     *
     * @return the value of member.weChatNumber
     *
     * @mbggenerated
     */
    public String getWechatnumber() {
        return wechatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.weChatNumber
     *
     * @param wechatnumber the value for member.weChatNumber
     *
     * @mbggenerated
     */
    public void setWechatnumber(String wechatnumber) {
        this.wechatnumber = wechatnumber == null ? null : wechatnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.address
     *
     * @return the value of member.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.address
     *
     * @param address the value for member.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.education
     *
     * @return the value of member.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.education
     *
     * @param education the value for member.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.classLevel
     *
     * @return the value of member.classLevel
     *
     * @mbggenerated
     */
    public Byte getClasslevel() {
        return classlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.classLevel
     *
     * @param classlevel the value for member.classLevel
     *
     * @mbggenerated
     */
    public void setClasslevel(Byte classlevel) {
        this.classlevel = classlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.avatar
     *
     * @return the value of member.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.avatar
     *
     * @param avatar the value for member.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.isActive
     *
     * @return the value of member.isActive
     *
     * @mbggenerated
     */
    public Boolean getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.isActive
     *
     * @param isactive the value for member.isActive
     *
     * @mbggenerated
     */
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.recommendationCode
     *
     * @return the value of member.recommendationCode
     *
     * @mbggenerated
     */
    public String getRecommendationcode() {
        return recommendationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.recommendationCode
     *
     * @param recommendationcode the value for member.recommendationCode
     *
     * @mbggenerated
     */
    public void setRecommendationcode(String recommendationcode) {
        this.recommendationcode = recommendationcode == null ? null : recommendationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.cardSeriesNumber
     *
     * @return the value of member.cardSeriesNumber
     *
     * @mbggenerated
     */
    public Long getCardseriesnumber() {
        return cardseriesnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.cardSeriesNumber
     *
     * @param cardseriesnumber the value for member.cardSeriesNumber
     *
     * @mbggenerated
     */
    public void setCardseriesnumber(Long cardseriesnumber) {
        this.cardseriesnumber = cardseriesnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.lastLoginDatetime
     *
     * @return the value of member.lastLoginDatetime
     *
     * @mbggenerated
     */
    public Date getLastlogindatetime() {
        return lastlogindatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.lastLoginDatetime
     *
     * @param lastlogindatetime the value for member.lastLoginDatetime
     *
     * @mbggenerated
     */
    public void setLastlogindatetime(Date lastlogindatetime) {
        this.lastlogindatetime = lastlogindatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reward_person
     *
     * @return the value of member.reward_person
     *
     * @mbggenerated
     */
    public Double getRewardPerson() {
        return rewardPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reward_person
     *
     * @param rewardPerson the value for member.reward_person
     *
     * @mbggenerated
     */
    public void setRewardPerson(Double rewardPerson) {
        this.rewardPerson = rewardPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reward_master
     *
     * @return the value of member.reward_master
     *
     * @mbggenerated
     */
    public Double getRewardMaster() {
        return rewardMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reward_master
     *
     * @param rewardMaster the value for member.reward_master
     *
     * @mbggenerated
     */
    public void setRewardMaster(Double rewardMaster) {
        this.rewardMaster = rewardMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reward_prentice
     *
     * @return the value of member.reward_prentice
     *
     * @mbggenerated
     */
    public Double getRewardPrentice() {
        return rewardPrentice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reward_prentice
     *
     * @param rewardPrentice the value for member.reward_prentice
     *
     * @mbggenerated
     */
    public void setRewardPrentice(Double rewardPrentice) {
        this.rewardPrentice = rewardPrentice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.starNum
     *
     * @return the value of member.starNum
     *
     * @mbggenerated
     */
    public Integer getStarnum() {
        return starnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.starNum
     *
     * @param starnum the value for member.starNum
     *
     * @mbggenerated
     */
    public void setStarnum(Integer starnum) {
        this.starnum = starnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.badReviewNum
     *
     * @return the value of member.badReviewNum
     *
     * @mbggenerated
     */
    public Integer getBadreviewnum() {
        return badreviewnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.badReviewNum
     *
     * @param badreviewnum the value for member.badReviewNum
     *
     * @mbggenerated
     */
    public void setBadreviewnum(Integer badreviewnum) {
        this.badreviewnum = badreviewnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.registrationTime
     *
     * @return the value of member.registrationTime
     *
     * @mbggenerated
     */
    public Date getRegistrationtime() {
        return registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.registrationTime
     *
     * @param registrationtime the value for member.registrationTime
     *
     * @mbggenerated
     */
    public void setRegistrationtime(Date registrationtime) {
        this.registrationtime = registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.customerServiceID
     *
     * @return the value of member.customerServiceID
     *
     * @mbggenerated
     */
    public Integer getCustomerserviceid() {
        return customerserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.customerServiceID
     *
     * @param customerserviceid the value for member.customerServiceID
     *
     * @mbggenerated
     */
    public void setCustomerserviceid(Integer customerserviceid) {
        this.customerserviceid = customerserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ureward
     *
     * @return the value of member.ureward
     *
     * @mbggenerated
     */
    public Double getUreward() {
        return ureward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ureward
     *
     * @param ureward the value for member.ureward
     *
     * @mbggenerated
     */
    public void setUreward(Double ureward) {
        this.ureward = ureward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.starLevel
     *
     * @return the value of member.starLevel
     *
     * @mbggenerated
     */
    public String getStarlevel() {
        return starlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.starLevel
     *
     * @param starlevel the value for member.starLevel
     *
     * @mbggenerated
     */
    public void setStarlevel(String starlevel) {
        this.starlevel = starlevel == null ? null : starlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.modificationTime
     *
     * @return the value of member.modificationTime
     *
     * @mbggenerated
     */
    public Date getModificationtime() {
        return modificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.modificationTime
     *
     * @param modificationtime the value for member.modificationTime
     *
     * @mbggenerated
     */
    public void setModificationtime(Date modificationtime) {
        this.modificationtime = modificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.informationTime
     *
     * @return the value of member.informationTime
     *
     * @mbggenerated
     */
    public Date getInformationtime() {
        return informationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.informationTime
     *
     * @param informationtime the value for member.informationTime
     *
     * @mbggenerated
     */
    public void setInformationtime(Date informationtime) {
        this.informationtime = informationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.userKey
     *
     * @return the value of member.userKey
     *
     * @mbggenerated
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.userKey
     *
     * @param userkey the value for member.userKey
     *
     * @mbggenerated
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey == null ? null : userkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.remove
     *
     * @return the value of member.remove
     *
     * @mbggenerated
     */
    public Integer getRemove() {
        return remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.remove
     *
     * @param remove the value for member.remove
     *
     * @mbggenerated
     */
    public void setRemove(Integer remove) {
        this.remove = remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.removetime
     *
     * @return the value of member.removetime
     *
     * @mbggenerated
     */
    public String getRemovetime() {
        return removetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.removetime
     *
     * @param removetime the value for member.removetime
     *
     * @mbggenerated
     */
    public void setRemovetime(String removetime) {
        this.removetime = removetime == null ? null : removetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", openid=").append(openid);
        sb.append(", userpwd=").append(userpwd);
        sb.append(", masterid=").append(masterid);
        sb.append(", idcardid=").append(idcardid);
        sb.append(", gender=").append(gender);
        sb.append(", phone=").append(phone);
        sb.append(", memberability=").append(memberability);
        sb.append(", wechatnumber=").append(wechatnumber);
        sb.append(", address=").append(address);
        sb.append(", education=").append(education);
        sb.append(", classlevel=").append(classlevel);
        sb.append(", avatar=").append(avatar);
        sb.append(", isactive=").append(isactive);
        sb.append(", recommendationcode=").append(recommendationcode);
        sb.append(", cardseriesnumber=").append(cardseriesnumber);
        sb.append(", lastlogindatetime=").append(lastlogindatetime);
        sb.append(", rewardPerson=").append(rewardPerson);
        sb.append(", rewardMaster=").append(rewardMaster);
        sb.append(", rewardPrentice=").append(rewardPrentice);
        sb.append(", starnum=").append(starnum);
        sb.append(", badreviewnum=").append(badreviewnum);
        sb.append(", registrationtime=").append(registrationtime);
        sb.append(", customerserviceid=").append(customerserviceid);
        sb.append(", email=").append(email);
        sb.append(", ureward=").append(ureward);
        sb.append(", starlevel=").append(starlevel);
        sb.append(", modificationtime=").append(modificationtime);
        sb.append(", informationtime=").append(informationtime);
        sb.append(", userkey=").append(userkey);
        sb.append(", remove=").append(remove);
        sb.append(", removetime=").append(removetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}