package cn.armylife.admin.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrderDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_id
     *
     * @mbggenerated
     */
    private Long orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_name
     *
     * @mbggenerated
     */
    private String orderDetailName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_png
     *
     * @mbggenerated
     */
    private String orderDetailPng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_total
     *
     * @mbggenerated
     */
    private BigDecimal orderDetailTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_num
     *
     * @mbggenerated
     */
    private Integer orderDetailNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_boxfee
     *
     * @mbggenerated
     */
    private BigDecimal orderDetailBoxfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_express_name
     *
     * @mbggenerated
     */
    private String orderExpressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_express_phone
     *
     * @mbggenerated
     */
    private String orderExpressPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_express_num
     *
     * @mbggenerated
     */
    private String orderExpressNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_express_desc
     *
     * @mbggenerated
     */
    private String orderExpressDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_id
     *
     * @return the value of order_detail.order_detail_id
     *
     * @mbggenerated
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_id
     *
     * @param orderDetailId the value for order_detail.order_detail_id
     *
     * @mbggenerated
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_id
     *
     * @return the value of order_detail.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_id
     *
     * @param orderId the value for order_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_name
     *
     * @return the value of order_detail.order_detail_name
     *
     * @mbggenerated
     */
    public String getOrderDetailName() {
        return orderDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_name
     *
     * @param orderDetailName the value for order_detail.order_detail_name
     *
     * @mbggenerated
     */
    public void setOrderDetailName(String orderDetailName) {
        this.orderDetailName = orderDetailName == null ? null : orderDetailName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_png
     *
     * @return the value of order_detail.order_detail_png
     *
     * @mbggenerated
     */
    public String getOrderDetailPng() {
        return orderDetailPng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_png
     *
     * @param orderDetailPng the value for order_detail.order_detail_png
     *
     * @mbggenerated
     */
    public void setOrderDetailPng(String orderDetailPng) {
        this.orderDetailPng = orderDetailPng == null ? null : orderDetailPng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_total
     *
     * @return the value of order_detail.order_detail_total
     *
     * @mbggenerated
     */
    public BigDecimal getOrderDetailTotal() {
        return orderDetailTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_total
     *
     * @param orderDetailTotal the value for order_detail.order_detail_total
     *
     * @mbggenerated
     */
    public void setOrderDetailTotal(BigDecimal orderDetailTotal) {
        this.orderDetailTotal = orderDetailTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_num
     *
     * @return the value of order_detail.order_detail_num
     *
     * @mbggenerated
     */
    public Integer getOrderDetailNum() {
        return orderDetailNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_num
     *
     * @param orderDetailNum the value for order_detail.order_detail_num
     *
     * @mbggenerated
     */
    public void setOrderDetailNum(Integer orderDetailNum) {
        this.orderDetailNum = orderDetailNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_boxfee
     *
     * @return the value of order_detail.order_detail_boxfee
     *
     * @mbggenerated
     */
    public BigDecimal getOrderDetailBoxfee() {
        return orderDetailBoxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_boxfee
     *
     * @param orderDetailBoxfee the value for order_detail.order_detail_boxfee
     *
     * @mbggenerated
     */
    public void setOrderDetailBoxfee(BigDecimal orderDetailBoxfee) {
        this.orderDetailBoxfee = orderDetailBoxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_express_name
     *
     * @return the value of order_detail.order_express_name
     *
     * @mbggenerated
     */
    public String getOrderExpressName() {
        return orderExpressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_express_name
     *
     * @param orderExpressName the value for order_detail.order_express_name
     *
     * @mbggenerated
     */
    public void setOrderExpressName(String orderExpressName) {
        this.orderExpressName = orderExpressName == null ? null : orderExpressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_express_phone
     *
     * @return the value of order_detail.order_express_phone
     *
     * @mbggenerated
     */
    public String getOrderExpressPhone() {
        return orderExpressPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_express_phone
     *
     * @param orderExpressPhone the value for order_detail.order_express_phone
     *
     * @mbggenerated
     */
    public void setOrderExpressPhone(String orderExpressPhone) {
        this.orderExpressPhone = orderExpressPhone == null ? null : orderExpressPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_express_num
     *
     * @return the value of order_detail.order_express_num
     *
     * @mbggenerated
     */
    public String getOrderExpressNum() {
        return orderExpressNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_express_num
     *
     * @param orderExpressNum the value for order_detail.order_express_num
     *
     * @mbggenerated
     */
    public void setOrderExpressNum(String orderExpressNum) {
        this.orderExpressNum = orderExpressNum == null ? null : orderExpressNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_express_desc
     *
     * @return the value of order_detail.order_express_desc
     *
     * @mbggenerated
     */
    public String getOrderExpressDesc() {
        return orderExpressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_express_desc
     *
     * @param orderExpressDesc the value for order_detail.order_express_desc
     *
     * @mbggenerated
     */
    public void setOrderExpressDesc(String orderExpressDesc) {
        this.orderExpressDesc = orderExpressDesc == null ? null : orderExpressDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderDetailName=").append(orderDetailName);
        sb.append(", orderDetailPng=").append(orderDetailPng);
        sb.append(", orderDetailTotal=").append(orderDetailTotal);
        sb.append(", orderDetailNum=").append(orderDetailNum);
        sb.append(", orderDetailBoxfee=").append(orderDetailBoxfee);
        sb.append(", orderExpressName=").append(orderExpressName);
        sb.append(", orderExpressPhone=").append(orderExpressPhone);
        sb.append(", orderExpressNum=").append(orderExpressNum);
        sb.append(", orderExpressDesc=").append(orderExpressDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}