package cn.armylife.admin.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Payments implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.payments_id
     *
     * @mbggenerated
     */
    private Long paymentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.vippay
     *
     * @mbggenerated
     */
    private Integer vippay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_name
     *
     * @mbggenerated
     */
    private Long payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.receiv_name
     *
     * @mbggenerated
     */
    private Long receivName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_total
     *
     * @mbggenerated
     */
    private BigDecimal payTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_desc
     *
     * @mbggenerated
     */
    private String payDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_order
     *
     * @mbggenerated
     */
    private Long payOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_number
     *
     * @mbggenerated
     */
    private String payNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_app
     *
     * @mbggenerated
     */
    private String payApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.creat_time
     *
     * @mbggenerated
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.pay_refund
     *
     * @mbggenerated
     */
    private Integer payRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.refund_desc
     *
     * @mbggenerated
     */
    private String refundDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.refund_total
     *
     * @mbggenerated
     */
    private BigDecimal refundTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.refuns_time
     *
     * @mbggenerated
     */
    private String refunsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.refunds_number
     *
     * @mbggenerated
     */
    private String refundsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payments
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.payments_id
     *
     * @return the value of payments.payments_id
     *
     * @mbggenerated
     */
    public Long getPaymentsId() {
        return paymentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.payments_id
     *
     * @param paymentsId the value for payments.payments_id
     *
     * @mbggenerated
     */
    public void setPaymentsId(Long paymentsId) {
        this.paymentsId = paymentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.order_id
     *
     * @return the value of payments.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.order_id
     *
     * @param orderId the value for payments.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.vippay
     *
     * @return the value of payments.vippay
     *
     * @mbggenerated
     */
    public Integer getVippay() {
        return vippay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.vippay
     *
     * @param vippay the value for payments.vippay
     *
     * @mbggenerated
     */
    public void setVippay(Integer vippay) {
        this.vippay = vippay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_name
     *
     * @return the value of payments.pay_name
     *
     * @mbggenerated
     */
    public Long getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_name
     *
     * @param payName the value for payments.pay_name
     *
     * @mbggenerated
     */
    public void setPayName(Long payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.receiv_name
     *
     * @return the value of payments.receiv_name
     *
     * @mbggenerated
     */
    public Long getReceivName() {
        return receivName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.receiv_name
     *
     * @param receivName the value for payments.receiv_name
     *
     * @mbggenerated
     */
    public void setReceivName(Long receivName) {
        this.receivName = receivName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_total
     *
     * @return the value of payments.pay_total
     *
     * @mbggenerated
     */
    public BigDecimal getPayTotal() {
        return payTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_total
     *
     * @param payTotal the value for payments.pay_total
     *
     * @mbggenerated
     */
    public void setPayTotal(BigDecimal payTotal) {
        this.payTotal = payTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_desc
     *
     * @return the value of payments.pay_desc
     *
     * @mbggenerated
     */
    public String getPayDesc() {
        return payDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_desc
     *
     * @param payDesc the value for payments.pay_desc
     *
     * @mbggenerated
     */
    public void setPayDesc(String payDesc) {
        this.payDesc = payDesc == null ? null : payDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_status
     *
     * @return the value of payments.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_status
     *
     * @param payStatus the value for payments.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_order
     *
     * @return the value of payments.pay_order
     *
     * @mbggenerated
     */
    public Long getPayOrder() {
        return payOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_order
     *
     * @param payOrder the value for payments.pay_order
     *
     * @mbggenerated
     */
    public void setPayOrder(Long payOrder) {
        this.payOrder = payOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_number
     *
     * @return the value of payments.pay_number
     *
     * @mbggenerated
     */
    public String getPayNumber() {
        return payNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_number
     *
     * @param payNumber the value for payments.pay_number
     *
     * @mbggenerated
     */
    public void setPayNumber(String payNumber) {
        this.payNumber = payNumber == null ? null : payNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_app
     *
     * @return the value of payments.pay_app
     *
     * @mbggenerated
     */
    public String getPayApp() {
        return payApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_app
     *
     * @param payApp the value for payments.pay_app
     *
     * @mbggenerated
     */
    public void setPayApp(String payApp) {
        this.payApp = payApp == null ? null : payApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.creat_time
     *
     * @return the value of payments.creat_time
     *
     * @mbggenerated
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.creat_time
     *
     * @param creatTime the value for payments.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.end_time
     *
     * @return the value of payments.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.end_time
     *
     * @param endTime the value for payments.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.pay_refund
     *
     * @return the value of payments.pay_refund
     *
     * @mbggenerated
     */
    public Integer getPayRefund() {
        return payRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.pay_refund
     *
     * @param payRefund the value for payments.pay_refund
     *
     * @mbggenerated
     */
    public void setPayRefund(Integer payRefund) {
        this.payRefund = payRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.refund_desc
     *
     * @return the value of payments.refund_desc
     *
     * @mbggenerated
     */
    public String getRefundDesc() {
        return refundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.refund_desc
     *
     * @param refundDesc the value for payments.refund_desc
     *
     * @mbggenerated
     */
    public void setRefundDesc(String refundDesc) {
        this.refundDesc = refundDesc == null ? null : refundDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.refund_total
     *
     * @return the value of payments.refund_total
     *
     * @mbggenerated
     */
    public BigDecimal getRefundTotal() {
        return refundTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.refund_total
     *
     * @param refundTotal the value for payments.refund_total
     *
     * @mbggenerated
     */
    public void setRefundTotal(BigDecimal refundTotal) {
        this.refundTotal = refundTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.refuns_time
     *
     * @return the value of payments.refuns_time
     *
     * @mbggenerated
     */
    public String getRefunsTime() {
        return refunsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.refuns_time
     *
     * @param refunsTime the value for payments.refuns_time
     *
     * @mbggenerated
     */
    public void setRefunsTime(String refunsTime) {
        this.refunsTime = refunsTime == null ? null : refunsTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.refunds_number
     *
     * @return the value of payments.refunds_number
     *
     * @mbggenerated
     */
    public String getRefundsNumber() {
        return refundsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.refunds_number
     *
     * @param refundsNumber the value for payments.refunds_number
     *
     * @mbggenerated
     */
    public void setRefundsNumber(String refundsNumber) {
        this.refundsNumber = refundsNumber == null ? null : refundsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", paymentsId=").append(paymentsId);
        sb.append(", orderId=").append(orderId);
        sb.append(", vippay=").append(vippay);
        sb.append(", payName=").append(payName);
        sb.append(", receivName=").append(receivName);
        sb.append(", payTotal=").append(payTotal);
        sb.append(", payDesc=").append(payDesc);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", payOrder=").append(payOrder);
        sb.append(", payNumber=").append(payNumber);
        sb.append(", payApp=").append(payApp);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", payRefund=").append(payRefund);
        sb.append(", refundDesc=").append(refundDesc);
        sb.append(", refundTotal=").append(refundTotal);
        sb.append(", refunsTime=").append(refunsTime);
        sb.append(", refundsNumber=").append(refundsNumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}