package cn.armylife.admin.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PointsMallProducts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.points_mall_products_id
     *
     * @mbggenerated
     */
    private Long pointsMallProductsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.using_integral
     *
     * @mbggenerated
     */
    private Integer usingIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.usage_amount
     *
     * @mbggenerated
     */
    private BigDecimal usageAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.original_price
     *
     * @mbggenerated
     */
    private BigDecimal originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.trade_name
     *
     * @mbggenerated
     */
    private String tradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.commodity_pictures
     *
     * @mbggenerated
     */
    private String commodityPictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.commodity_details
     *
     * @mbggenerated
     */
    private String commodityDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.respective_area
     *
     * @mbggenerated
     */
    private Long respectiveArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_mall_products.adding_time
     *
     * @mbggenerated
     */
    private Date addingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.points_mall_products_id
     *
     * @return the value of points_mall_products.points_mall_products_id
     *
     * @mbggenerated
     */
    public Long getPointsMallProductsId() {
        return pointsMallProductsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.points_mall_products_id
     *
     * @param pointsMallProductsId the value for points_mall_products.points_mall_products_id
     *
     * @mbggenerated
     */
    public void setPointsMallProductsId(Long pointsMallProductsId) {
        this.pointsMallProductsId = pointsMallProductsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.using_integral
     *
     * @return the value of points_mall_products.using_integral
     *
     * @mbggenerated
     */
    public Integer getUsingIntegral() {
        return usingIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.using_integral
     *
     * @param usingIntegral the value for points_mall_products.using_integral
     *
     * @mbggenerated
     */
    public void setUsingIntegral(Integer usingIntegral) {
        this.usingIntegral = usingIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.usage_amount
     *
     * @return the value of points_mall_products.usage_amount
     *
     * @mbggenerated
     */
    public BigDecimal getUsageAmount() {
        return usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.usage_amount
     *
     * @param usageAmount the value for points_mall_products.usage_amount
     *
     * @mbggenerated
     */
    public void setUsageAmount(BigDecimal usageAmount) {
        this.usageAmount = usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.original_price
     *
     * @return the value of points_mall_products.original_price
     *
     * @mbggenerated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.original_price
     *
     * @param originalPrice the value for points_mall_products.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.trade_name
     *
     * @return the value of points_mall_products.trade_name
     *
     * @mbggenerated
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.trade_name
     *
     * @param tradeName the value for points_mall_products.trade_name
     *
     * @mbggenerated
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName == null ? null : tradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.commodity_pictures
     *
     * @return the value of points_mall_products.commodity_pictures
     *
     * @mbggenerated
     */
    public String getCommodityPictures() {
        return commodityPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.commodity_pictures
     *
     * @param commodityPictures the value for points_mall_products.commodity_pictures
     *
     * @mbggenerated
     */
    public void setCommodityPictures(String commodityPictures) {
        this.commodityPictures = commodityPictures == null ? null : commodityPictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.commodity_details
     *
     * @return the value of points_mall_products.commodity_details
     *
     * @mbggenerated
     */
    public String getCommodityDetails() {
        return commodityDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.commodity_details
     *
     * @param commodityDetails the value for points_mall_products.commodity_details
     *
     * @mbggenerated
     */
    public void setCommodityDetails(String commodityDetails) {
        this.commodityDetails = commodityDetails == null ? null : commodityDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.respective_area
     *
     * @return the value of points_mall_products.respective_area
     *
     * @mbggenerated
     */
    public Long getRespectiveArea() {
        return respectiveArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.respective_area
     *
     * @param respectiveArea the value for points_mall_products.respective_area
     *
     * @mbggenerated
     */
    public void setRespectiveArea(Long respectiveArea) {
        this.respectiveArea = respectiveArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_mall_products.adding_time
     *
     * @return the value of points_mall_products.adding_time
     *
     * @mbggenerated
     */
    public Date getAddingTime() {
        return addingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_mall_products.adding_time
     *
     * @param addingTime the value for points_mall_products.adding_time
     *
     * @mbggenerated
     */
    public void setAddingTime(Date addingTime) {
        this.addingTime = addingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pointsMallProductsId=").append(pointsMallProductsId);
        sb.append(", usingIntegral=").append(usingIntegral);
        sb.append(", usageAmount=").append(usageAmount);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", tradeName=").append(tradeName);
        sb.append(", commodityPictures=").append(commodityPictures);
        sb.append(", commodityDetails=").append(commodityDetails);
        sb.append(", respectiveArea=").append(respectiveArea);
        sb.append(", addingTime=").append(addingTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}