package cn.armylife.admin.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PointsExchangeRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.points_exchange_record_id
     *
     * @mbggenerated
     */
    private Long pointsExchangeRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.using_integral
     *
     * @mbggenerated
     */
    private Integer usingIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.usage_amount
     *
     * @mbggenerated
     */
    private BigDecimal usageAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.exchange_time
     *
     * @mbggenerated
     */
    private Date exchangeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.items_exchanged
     *
     * @mbggenerated
     */
    private String itemsExchanged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.logistics_number
     *
     * @mbggenerated
     */
    private String logisticsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.user_address
     *
     * @mbggenerated
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_exchange_record.product_detail_id
     *
     * @mbggenerated
     */
    private Long productDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.points_exchange_record_id
     *
     * @return the value of points_exchange_record.points_exchange_record_id
     *
     * @mbggenerated
     */
    public Long getPointsExchangeRecordId() {
        return pointsExchangeRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.points_exchange_record_id
     *
     * @param pointsExchangeRecordId the value for points_exchange_record.points_exchange_record_id
     *
     * @mbggenerated
     */
    public void setPointsExchangeRecordId(Long pointsExchangeRecordId) {
        this.pointsExchangeRecordId = pointsExchangeRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.using_integral
     *
     * @return the value of points_exchange_record.using_integral
     *
     * @mbggenerated
     */
    public Integer getUsingIntegral() {
        return usingIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.using_integral
     *
     * @param usingIntegral the value for points_exchange_record.using_integral
     *
     * @mbggenerated
     */
    public void setUsingIntegral(Integer usingIntegral) {
        this.usingIntegral = usingIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.usage_amount
     *
     * @return the value of points_exchange_record.usage_amount
     *
     * @mbggenerated
     */
    public BigDecimal getUsageAmount() {
        return usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.usage_amount
     *
     * @param usageAmount the value for points_exchange_record.usage_amount
     *
     * @mbggenerated
     */
    public void setUsageAmount(BigDecimal usageAmount) {
        this.usageAmount = usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.exchange_time
     *
     * @return the value of points_exchange_record.exchange_time
     *
     * @mbggenerated
     */
    public Date getExchangeTime() {
        return exchangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.exchange_time
     *
     * @param exchangeTime the value for points_exchange_record.exchange_time
     *
     * @mbggenerated
     */
    public void setExchangeTime(Date exchangeTime) {
        this.exchangeTime = exchangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.items_exchanged
     *
     * @return the value of points_exchange_record.items_exchanged
     *
     * @mbggenerated
     */
    public String getItemsExchanged() {
        return itemsExchanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.items_exchanged
     *
     * @param itemsExchanged the value for points_exchange_record.items_exchanged
     *
     * @mbggenerated
     */
    public void setItemsExchanged(String itemsExchanged) {
        this.itemsExchanged = itemsExchanged == null ? null : itemsExchanged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.logistics_number
     *
     * @return the value of points_exchange_record.logistics_number
     *
     * @mbggenerated
     */
    public String getLogisticsNumber() {
        return logisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.logistics_number
     *
     * @param logisticsNumber the value for points_exchange_record.logistics_number
     *
     * @mbggenerated
     */
    public void setLogisticsNumber(String logisticsNumber) {
        this.logisticsNumber = logisticsNumber == null ? null : logisticsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.user_id
     *
     * @return the value of points_exchange_record.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.user_id
     *
     * @param userId the value for points_exchange_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.user_name
     *
     * @return the value of points_exchange_record.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.user_name
     *
     * @param userName the value for points_exchange_record.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.user_phone
     *
     * @return the value of points_exchange_record.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.user_phone
     *
     * @param userPhone the value for points_exchange_record.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.user_address
     *
     * @return the value of points_exchange_record.user_address
     *
     * @mbggenerated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.user_address
     *
     * @param userAddress the value for points_exchange_record.user_address
     *
     * @mbggenerated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.product_id
     *
     * @return the value of points_exchange_record.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.product_id
     *
     * @param productId the value for points_exchange_record.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_exchange_record.product_detail_id
     *
     * @return the value of points_exchange_record.product_detail_id
     *
     * @mbggenerated
     */
    public Long getProductDetailId() {
        return productDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_exchange_record.product_detail_id
     *
     * @param productDetailId the value for points_exchange_record.product_detail_id
     *
     * @mbggenerated
     */
    public void setProductDetailId(Long productDetailId) {
        this.productDetailId = productDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pointsExchangeRecordId=").append(pointsExchangeRecordId);
        sb.append(", usingIntegral=").append(usingIntegral);
        sb.append(", usageAmount=").append(usageAmount);
        sb.append(", exchangeTime=").append(exchangeTime);
        sb.append(", itemsExchanged=").append(itemsExchanged);
        sb.append(", logisticsNumber=").append(logisticsNumber);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userAddress=").append(userAddress);
        sb.append(", productId=").append(productId);
        sb.append(", productDetailId=").append(productDetailId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}