package cn.armylife.payments.serviceimpl;

import cn.armylife.common.domain.AfterOrder;
import cn.armylife.common.domain.Member;
import cn.armylife.common.domain.Payments;
import cn.armylife.common.domain.ShopOrder;
import cn.armylife.payments.feignservice.IntegralService;
import cn.armylife.payments.mapper.AfterOrderMapper;
import cn.armylife.payments.mapper.PaymentsMapper;
import cn.armylife.payments.service.PayMentsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

@Service
public class PayMemtsServiceImpl implements PayMentsService {

    @Autowired
    PaymentsMapper paymentsMapper;
    @Autowired
    AfterOrderMapper afterOrderMapper;
    @Autowired
    IntegralService integralService;

    /**
     * 查询商铺收入金额
     * @param receivName
     * @return
     */
    public Payments SelectPayForShop(Long receivName){
        return paymentsMapper.SelectPayForShop(receivName);
    };

    /**
     * 查询商铺退款金额
     * @param receivName
     * @return
     */
    public Payments SelectRefundForShop(Long receivName){
        return paymentsMapper.SelectRefundForShop(receivName);
    };

    /**
     * 支付完成,更新支付数据
     * @param payments
     * @return
     */
    public int updatePayMentsForCallback(Payments payments){
        return paymentsMapper.updatePayMentsForCallback(payments);
    };

    /**
     * 查询支付记录(通过订单号)
     * @param orderId
     * @return
     */
    public Payments selectPaments(Long orderId){
        return paymentsMapper.selectPaments(orderId);
    };

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *添加支付记录
     * @mbggenerated
     */
    public int insert(Payments record){
        return paymentsMapper.insert(record);
    };


    public int updateafterOrderForPay(AfterOrder afterOrder){
        return afterOrderMapper.updateafterOrderForPay(afterOrder);
    };

    /**
     * 查询订单
     * @param ordersId
     * @return
     */
    public ShopOrder selectOrder(Long ordersId){
        return paymentsMapper.selectOrder(ordersId);
    };

    /**
     * 查询子订单
     * @param ordersId
     * @return
     */
    public AfterOrder selectAfterOrder(Long ordersId){
        return paymentsMapper.selectAfterOrder(ordersId);
    };

    /**
     * 更新订单状态
     * @param shopOrder
     * @return
     */
    @Override
    public int updateShopOrder(ShopOrder shopOrder){
        return paymentsMapper.updateShopOrder(shopOrder);
    };

    @Override
    public Payments selectOrderForPayments(Long paymentsId){
        return paymentsMapper.selectOrderForPayments(paymentsId);
    };

    @Override
    public int updateShop(Member member){
        return paymentsMapper.updateShop(member);
    };

    @Override
    public Member selectMember(Long memberId){
        return paymentsMapper.selectMember(memberId);
    };

    public int payintegralIncrease(Integer total, HttpServletRequest request){
        HttpSession session=request.getSession();
        Member member=(Member)session.getAttribute("Student");
        return integralService.payintegralIncrease(total,member.getMemberId());
    };

    public Member selectMemberForOpenid(String memberWechat){
        return paymentsMapper.selectMemberForOpenid(memberWechat);
    };

}

