package cn.armylife.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class AfterOrderDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_order_detail.after_order_detail_id
     *
     * @mbggenerated
     */
    private Long afterOrderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_order_detail.after_order_id
     *
     * @mbggenerated
     */
    private Long afterOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_order_detail.after_order_name
     *
     * @mbggenerated
     */
    private String afterOrderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_order_detail.after_order_num
     *
     * @mbggenerated
     */
    private String afterOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_order_detail.after_order_png
     *
     * @mbggenerated
     */
    private String afterOrderPng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_order_detail.after_order_total
     *
     * @mbggenerated
     */
    private BigDecimal afterOrderTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after_order_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_order_detail.after_order_detail_id
     *
     * @return the value of after_order_detail.after_order_detail_id
     *
     * @mbggenerated
     */
    public Long getAfterOrderDetailId() {
        return afterOrderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_order_detail.after_order_detail_id
     *
     * @param afterOrderDetailId the value for after_order_detail.after_order_detail_id
     *
     * @mbggenerated
     */
    public void setAfterOrderDetailId(Long afterOrderDetailId) {
        this.afterOrderDetailId = afterOrderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_order_detail.after_order_id
     *
     * @return the value of after_order_detail.after_order_id
     *
     * @mbggenerated
     */
    public Long getAfterOrderId() {
        return afterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_order_detail.after_order_id
     *
     * @param afterOrderId the value for after_order_detail.after_order_id
     *
     * @mbggenerated
     */
    public void setAfterOrderId(Long afterOrderId) {
        this.afterOrderId = afterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_order_detail.after_order_name
     *
     * @return the value of after_order_detail.after_order_name
     *
     * @mbggenerated
     */
    public String getAfterOrderName() {
        return afterOrderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_order_detail.after_order_name
     *
     * @param afterOrderName the value for after_order_detail.after_order_name
     *
     * @mbggenerated
     */
    public void setAfterOrderName(String afterOrderName) {
        this.afterOrderName = afterOrderName == null ? null : afterOrderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_order_detail.after_order_num
     *
     * @return the value of after_order_detail.after_order_num
     *
     * @mbggenerated
     */
    public String getAfterOrderNum() {
        return afterOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_order_detail.after_order_num
     *
     * @param afterOrderNum the value for after_order_detail.after_order_num
     *
     * @mbggenerated
     */
    public void setAfterOrderNum(String afterOrderNum) {
        this.afterOrderNum = afterOrderNum == null ? null : afterOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_order_detail.after_order_png
     *
     * @return the value of after_order_detail.after_order_png
     *
     * @mbggenerated
     */
    public String getAfterOrderPng() {
        return afterOrderPng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_order_detail.after_order_png
     *
     * @param afterOrderPng the value for after_order_detail.after_order_png
     *
     * @mbggenerated
     */
    public void setAfterOrderPng(String afterOrderPng) {
        this.afterOrderPng = afterOrderPng == null ? null : afterOrderPng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_order_detail.after_order_total
     *
     * @return the value of after_order_detail.after_order_total
     *
     * @mbggenerated
     */
    public BigDecimal getAfterOrderTotal() {
        return afterOrderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_order_detail.after_order_total
     *
     * @param afterOrderTotal the value for after_order_detail.after_order_total
     *
     * @mbggenerated
     */
    public void setAfterOrderTotal(BigDecimal afterOrderTotal) {
        this.afterOrderTotal = afterOrderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_order_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", afterOrderDetailId=").append(afterOrderDetailId);
        sb.append(", afterOrderId=").append(afterOrderId);
        sb.append(", afterOrderName=").append(afterOrderName);
        sb.append(", afterOrderNum=").append(afterOrderNum);
        sb.append(", afterOrderPng=").append(afterOrderPng);
        sb.append(", afterOrderTotal=").append(afterOrderTotal);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}