package cn.armylife.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class DeliveryOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.delivery_orders_id
     *
     * @mbggenerated
     */
    private Integer deliveryOrdersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.orders_id
     *
     * @mbggenerated
     */
    private Long ordersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.delivery_user_id
     *
     * @mbggenerated
     */
    private Long deliveryUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.delivery_address
     *
     * @mbggenerated
     */
    private String deliveryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.delivery_total
     *
     * @mbggenerated
     */
    private BigDecimal deliveryTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    private ShopOrder shopOrder;

    private Member member;

    private BigDecimal total;//查询全部订单时的订单总金额

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public Member getMember() {
        return member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    public ShopOrder getShopOrder() {
        return shopOrder;
    }

    public void setShopOrder(ShopOrder shopOrder) {
        this.shopOrder = shopOrder;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.delivery_orders_id
     *
     * @return the value of delivery_order.delivery_orders_id
     *
     * @mbggenerated
     */
    public Integer getDeliveryOrdersId() {
        return deliveryOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.delivery_orders_id
     *
     * @param deliveryOrdersId the value for delivery_order.delivery_orders_id
     *
     * @mbggenerated
     */
    public void setDeliveryOrdersId(Integer deliveryOrdersId) {
        this.deliveryOrdersId = deliveryOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.orders_id
     *
     * @return the value of delivery_order.orders_id
     *
     * @mbggenerated
     */
    public Long getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.orders_id
     *
     * @param ordersId the value for delivery_order.orders_id
     *
     * @mbggenerated
     */
    public void setOrdersId(Long ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.delivery_user_id
     *
     * @return the value of delivery_order.delivery_user_id
     *
     * @mbggenerated
     */
    public Long getDeliveryUserId() {
        return deliveryUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.delivery_user_id
     *
     * @param deliveryUserId the value for delivery_order.delivery_user_id
     *
     * @mbggenerated
     */
    public void setDeliveryUserId(Long deliveryUserId) {
        this.deliveryUserId = deliveryUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.delivery_address
     *
     * @return the value of delivery_order.delivery_address
     *
     * @mbggenerated
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.delivery_address
     *
     * @param deliveryAddress the value for delivery_order.delivery_address
     *
     * @mbggenerated
     */
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress == null ? null : deliveryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.user_phone
     *
     * @return the value of delivery_order.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.user_phone
     *
     * @param userPhone the value for delivery_order.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.user_name
     *
     * @return the value of delivery_order.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.user_name
     *
     * @param userName the value for delivery_order.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.delivery_total
     *
     * @return the value of delivery_order.delivery_total
     *
     * @mbggenerated
     */
    public BigDecimal getDeliveryTotal() {
        return deliveryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.delivery_total
     *
     * @param deliveryTotal the value for delivery_order.delivery_total
     *
     * @mbggenerated
     */
    public void setDeliveryTotal(BigDecimal deliveryTotal) {
        this.deliveryTotal = deliveryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.status
     *
     * @return the value of delivery_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.status
     *
     * @param status the value for delivery_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryOrdersId=").append(deliveryOrdersId);
        sb.append(", ordersId=").append(ordersId);
        sb.append(", deliveryUserId=").append(deliveryUserId);
        sb.append(", deliveryAddress=").append(deliveryAddress);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userName=").append(userName);
        sb.append(", deliveryTotal=").append(deliveryTotal);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}