package cn.armylife.common.domain;

import java.io.Serializable;
import java.util.Date;

public class Hairvip implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.hairvip_id
     *
     * @mbggenerated
     */
    private Long hairvipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.vip_id
     *
     * @mbggenerated
     */
    private Long vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.hairvip_name
     *
     * @mbggenerated
     */
    private String hairvipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.hairvip_phone
     *
     * @mbggenerated
     */
    private String hairvipPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.hairvip_num
     *
     * @mbggenerated
     */
    private String hairvipNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.haivip_address
     *
     * @mbggenerated
     */
    private String haivipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.creat_time
     *
     * @mbggenerated
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hairvip.is
     *
     * @mbggenerated
     */
    private Integer is;

    private ShopOrder shopOrder;

    public ShopOrder getShopOrder() {
        return shopOrder;
    }

    public void setShopOrder(ShopOrder shopOrder) {
        this.shopOrder = shopOrder;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.hairvip_id
     *
     * @return the value of hairvip.hairvip_id
     *
     * @mbggenerated
     */
    public Long getHairvipId() {
        return hairvipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.hairvip_id
     *
     * @param hairvipId the value for hairvip.hairvip_id
     *
     * @mbggenerated
     */
    public void setHairvipId(Long hairvipId) {
        this.hairvipId = hairvipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.vip_id
     *
     * @return the value of hairvip.vip_id
     *
     * @mbggenerated
     */
    public Long getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.vip_id
     *
     * @param vipId the value for hairvip.vip_id
     *
     * @mbggenerated
     */
    public void setVipId(Long vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.hairvip_name
     *
     * @return the value of hairvip.hairvip_name
     *
     * @mbggenerated
     */
    public String getHairvipName() {
        return hairvipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.hairvip_name
     *
     * @param hairvipName the value for hairvip.hairvip_name
     *
     * @mbggenerated
     */
    public void setHairvipName(String hairvipName) {
        this.hairvipName = hairvipName == null ? null : hairvipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.hairvip_phone
     *
     * @return the value of hairvip.hairvip_phone
     *
     * @mbggenerated
     */
    public String getHairvipPhone() {
        return hairvipPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.hairvip_phone
     *
     * @param hairvipPhone the value for hairvip.hairvip_phone
     *
     * @mbggenerated
     */
    public void setHairvipPhone(String hairvipPhone) {
        this.hairvipPhone = hairvipPhone == null ? null : hairvipPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.hairvip_num
     *
     * @return the value of hairvip.hairvip_num
     *
     * @mbggenerated
     */
    public String getHairvipNum() {
        return hairvipNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.hairvip_num
     *
     * @param hairvipNum the value for hairvip.hairvip_num
     *
     * @mbggenerated
     */
    public void setHairvipNum(String hairvipNum) {
        this.hairvipNum = hairvipNum == null ? null : hairvipNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.haivip_address
     *
     * @return the value of hairvip.haivip_address
     *
     * @mbggenerated
     */
    public String getHaivipAddress() {
        return haivipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.haivip_address
     *
     * @param haivipAddress the value for hairvip.haivip_address
     *
     * @mbggenerated
     */
    public void setHaivipAddress(String haivipAddress) {
        this.haivipAddress = haivipAddress == null ? null : haivipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.end_time
     *
     * @return the value of hairvip.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.end_time
     *
     * @param endTime the value for hairvip.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.creat_time
     *
     * @return the value of hairvip.creat_time
     *
     * @mbggenerated
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.creat_time
     *
     * @param creatTime the value for hairvip.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hairvip.is
     *
     * @return the value of hairvip.is
     *
     * @mbggenerated
     */
    public Integer getIs() {
        return is;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hairvip.is
     *
     * @param is the value for hairvip.is
     *
     * @mbggenerated
     */
    public void setIs(Integer is) {
        this.is = is;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hairvipId=").append(hairvipId);
        sb.append(", vipId=").append(vipId);
        sb.append(", hairvipName=").append(hairvipName);
        sb.append(", hairvipPhone=").append(hairvipPhone);
        sb.append(", hairvipNum=").append(hairvipNum);
        sb.append(", haivipAddress=").append(haivipAddress);
        sb.append(", endTime=").append(endTime);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", is=").append(is);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}