package cn.armylife.common.domain;

import java.io.Serializable;

public class IntegralUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_user.integral_user_id
     *
     * @mbggenerated
     */
    private Long integralUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_user.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table integral_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_user.integral_user_id
     *
     * @return the value of integral_user.integral_user_id
     *
     * @mbggenerated
     */
    public Long getIntegralUserId() {
        return integralUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_user.integral_user_id
     *
     * @param integralUserId the value for integral_user.integral_user_id
     *
     * @mbggenerated
     */
    public void setIntegralUserId(Long integralUserId) {
        this.integralUserId = integralUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_user.user_id
     *
     * @return the value of integral_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_user.user_id
     *
     * @param userId the value for integral_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_user.integral
     *
     * @return the value of integral_user.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_user.integral
     *
     * @param integral the value for integral_user.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", integralUserId=").append(integralUserId);
        sb.append(", userId=").append(userId);
        sb.append(", integral=").append(integral);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}