package cn.armylife.common.Domain;

import java.io.Serializable;
import java.util.Date;

public class IntegralRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_record.integral_record_id
     *
     * @mbggenerated
     */
    private Long integralRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_record.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_record.record
     *
     * @mbggenerated
     */
    private String record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_record.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table integral_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_record.integral_record_id
     *
     * @return the value of integral_record.integral_record_id
     *
     * @mbggenerated
     */
    public Long getIntegralRecordId() {
        return integralRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_record.integral_record_id
     *
     * @param integralRecordId the value for integral_record.integral_record_id
     *
     * @mbggenerated
     */
    public void setIntegralRecordId(Long integralRecordId) {
        this.integralRecordId = integralRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_record.user_id
     *
     * @return the value of integral_record.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_record.user_id
     *
     * @param userId the value for integral_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_record.record
     *
     * @return the value of integral_record.record
     *
     * @mbggenerated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_record.record
     *
     * @param record the value for integral_record.record
     *
     * @mbggenerated
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_record.time
     *
     * @return the value of integral_record.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_record.time
     *
     * @param time the value for integral_record.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", integralRecordId=").append(integralRecordId);
        sb.append(", userId=").append(userId);
        sb.append(", record=").append(record);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}