package cn.armylife.common.Domain;

import java.io.Serializable;

public class MallProductsPicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_picture.mall_products_pocture_id
     *
     * @mbggenerated
     */
    private Long mallProductsPoctureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_picture.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_picture.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_products_picture
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_picture.mall_products_pocture_id
     *
     * @return the value of mall_products_picture.mall_products_pocture_id
     *
     * @mbggenerated
     */
    public Long getMallProductsPoctureId() {
        return mallProductsPoctureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_picture.mall_products_pocture_id
     *
     * @param mallProductsPoctureId the value for mall_products_picture.mall_products_pocture_id
     *
     * @mbggenerated
     */
    public void setMallProductsPoctureId(Long mallProductsPoctureId) {
        this.mallProductsPoctureId = mallProductsPoctureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_picture.product_id
     *
     * @return the value of mall_products_picture.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_picture.product_id
     *
     * @param productId the value for mall_products_picture.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_picture.picture_url
     *
     * @return the value of mall_products_picture.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_picture.picture_url
     *
     * @param pictureUrl the value for mall_products_picture.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_products_picture
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mallProductsPoctureId=").append(mallProductsPoctureId);
        sb.append(", productId=").append(productId);
        sb.append(", pictureUrl=").append(pictureUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}