package cn.armylife.common.domain;

import java.io.Serializable;

public class MallProductsDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.mall_products_detail_id
     *
     * @mbggenerated
     */
    private Long mallProductsDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.mall_product_id
     *
     * @mbggenerated
     */
    private Long mallProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.commodity_model
     *
     * @mbggenerated
     */
    private String commodityModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.commodity_color
     *
     * @mbggenerated
     */
    private String commodityColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.commodity_material
     *
     * @mbggenerated
     */
    private String commodityMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.commodity_weight
     *
     * @mbggenerated
     */
    private String commodityWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.product_specification
     *
     * @mbggenerated
     */
    private String productSpecification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_products_detail.editing_time
     *
     * @mbggenerated
     */
    private String editingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_products_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.mall_products_detail_id
     *
     * @return the value of mall_products_detail.mall_products_detail_id
     *
     * @mbggenerated
     */
    public Long getMallProductsDetailId() {
        return mallProductsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.mall_products_detail_id
     *
     * @param mallProductsDetailId the value for mall_products_detail.mall_products_detail_id
     *
     * @mbggenerated
     */
    public void setMallProductsDetailId(Long mallProductsDetailId) {
        this.mallProductsDetailId = mallProductsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.mall_product_id
     *
     * @return the value of mall_products_detail.mall_product_id
     *
     * @mbggenerated
     */
    public Long getMallProductId() {
        return mallProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.mall_product_id
     *
     * @param mallProductId the value for mall_products_detail.mall_product_id
     *
     * @mbggenerated
     */
    public void setMallProductId(Long mallProductId) {
        this.mallProductId = mallProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.commodity_model
     *
     * @return the value of mall_products_detail.commodity_model
     *
     * @mbggenerated
     */
    public String getCommodityModel() {
        return commodityModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.commodity_model
     *
     * @param commodityModel the value for mall_products_detail.commodity_model
     *
     * @mbggenerated
     */
    public void setCommodityModel(String commodityModel) {
        this.commodityModel = commodityModel == null ? null : commodityModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.commodity_color
     *
     * @return the value of mall_products_detail.commodity_color
     *
     * @mbggenerated
     */
    public String getCommodityColor() {
        return commodityColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.commodity_color
     *
     * @param commodityColor the value for mall_products_detail.commodity_color
     *
     * @mbggenerated
     */
    public void setCommodityColor(String commodityColor) {
        this.commodityColor = commodityColor == null ? null : commodityColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.commodity_material
     *
     * @return the value of mall_products_detail.commodity_material
     *
     * @mbggenerated
     */
    public String getCommodityMaterial() {
        return commodityMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.commodity_material
     *
     * @param commodityMaterial the value for mall_products_detail.commodity_material
     *
     * @mbggenerated
     */
    public void setCommodityMaterial(String commodityMaterial) {
        this.commodityMaterial = commodityMaterial == null ? null : commodityMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.commodity_weight
     *
     * @return the value of mall_products_detail.commodity_weight
     *
     * @mbggenerated
     */
    public String getCommodityWeight() {
        return commodityWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.commodity_weight
     *
     * @param commodityWeight the value for mall_products_detail.commodity_weight
     *
     * @mbggenerated
     */
    public void setCommodityWeight(String commodityWeight) {
        this.commodityWeight = commodityWeight == null ? null : commodityWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.product_specification
     *
     * @return the value of mall_products_detail.product_specification
     *
     * @mbggenerated
     */
    public String getProductSpecification() {
        return productSpecification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.product_specification
     *
     * @param productSpecification the value for mall_products_detail.product_specification
     *
     * @mbggenerated
     */
    public void setProductSpecification(String productSpecification) {
        this.productSpecification = productSpecification == null ? null : productSpecification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_products_detail.editing_time
     *
     * @return the value of mall_products_detail.editing_time
     *
     * @mbggenerated
     */
    public String getEditingTime() {
        return editingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_products_detail.editing_time
     *
     * @param editingTime the value for mall_products_detail.editing_time
     *
     * @mbggenerated
     */
    public void setEditingTime(String editingTime) {
        this.editingTime = editingTime == null ? null : editingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_products_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mallProductsDetailId=").append(mallProductsDetailId);
        sb.append(", mallProductId=").append(mallProductId);
        sb.append(", commodityModel=").append(commodityModel);
        sb.append(", commodityColor=").append(commodityColor);
        sb.append(", commodityMaterial=").append(commodityMaterial);
        sb.append(", commodityWeight=").append(commodityWeight);
        sb.append(", productSpecification=").append(productSpecification);
        sb.append(", editingTime=").append(editingTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}