package cn.armylife.common.domain;

import java.io.Serializable;
import java.util.Date;

public class MemberDeliveryaddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deliveryaddress.address_id
     *
     * @mbggenerated
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deliveryaddress.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deliveryaddress.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deliveryaddress.member_name
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deliveryaddress.member_phone
     *
     * @mbggenerated
     */
    private String memberPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_deliveryaddress.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_deliveryaddress
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deliveryaddress.address_id
     *
     * @return the value of member_deliveryaddress.address_id
     *
     * @mbggenerated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deliveryaddress.address_id
     *
     * @param addressId the value for member_deliveryaddress.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deliveryaddress.member_id
     *
     * @return the value of member_deliveryaddress.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deliveryaddress.member_id
     *
     * @param memberId the value for member_deliveryaddress.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deliveryaddress.address
     *
     * @return the value of member_deliveryaddress.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deliveryaddress.address
     *
     * @param address the value for member_deliveryaddress.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deliveryaddress.member_name
     *
     * @return the value of member_deliveryaddress.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deliveryaddress.member_name
     *
     * @param memberName the value for member_deliveryaddress.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deliveryaddress.member_phone
     *
     * @return the value of member_deliveryaddress.member_phone
     *
     * @mbggenerated
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deliveryaddress.member_phone
     *
     * @param memberPhone the value for member_deliveryaddress.member_phone
     *
     * @mbggenerated
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_deliveryaddress.creat_time
     *
     * @return the value of member_deliveryaddress.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_deliveryaddress.creat_time
     *
     * @param creatTime the value for member_deliveryaddress.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_deliveryaddress
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addressId=").append(addressId);
        sb.append(", memberId=").append(memberId);
        sb.append(", address=").append(address);
        sb.append(", memberName=").append(memberName);
        sb.append(", memberPhone=").append(memberPhone);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}