package cn.armylife.common.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shop_id
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.tag_id
     *
     * @mbggenerated
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_total
     *
     * @mbggenerated
     */
    private BigDecimal productTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbggenerated
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_desc
     *
     * @mbggenerated
     */
    private String productDesc;

    private ShopTag shopTag;

    private String orderNum;

    public String getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    public ShopTag getShopTag() {
        return shopTag;
    }

    public void setShopTag(ShopTag shopTag) {
        this.shopTag = shopTag;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_avator
     *
     * @mbggenerated
     */
    private String productAvator;

    private BigDecimal dayTotal;
    private int dayNum;
    private int monthNum;

    public BigDecimal getDayTotal() {
        return dayTotal;
    }

    public void setDayTotal(BigDecimal dayTotal) {
        this.dayTotal = dayTotal;
    }

    public int getDayNum() {
        return dayNum;
    }

    public void setDayNum(int dayNum) {
        this.dayNum = dayNum;
    }

    public int getMonthNum() {
        return monthNum;
    }

    public void setMonthNum(int monthNum) {
        this.monthNum = monthNum;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shop_id
     *
     * @return the value of product.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shop_id
     *
     * @param shopId the value for product.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.tag_id
     *
     * @return the value of product.tag_id
     *
     * @mbggenerated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.tag_id
     *
     * @param tagId the value for product.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_total
     *
     * @return the value of product.product_total
     *
     * @mbggenerated
     */
    public BigDecimal getProductTotal() {
        return productTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_total
     *
     * @param productTotal the value for product.product_total
     *
     * @mbggenerated
     */
    public void setProductTotal(BigDecimal productTotal) {
        this.productTotal = productTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbggenerated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbggenerated
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_desc
     *
     * @return the value of product.product_desc
     *
     * @mbggenerated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_desc
     *
     * @param productDesc the value for product.product_desc
     *
     * @mbggenerated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_avator
     *
     * @return the value of product.product_avator
     *
     * @mbggenerated
     */
    public String getProductAvator() {
        return productAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_avator
     *
     * @param productAvator the value for product.product_avator
     *
     * @mbggenerated
     */
    public void setProductAvator(String productAvator) {
        this.productAvator = productAvator == null ? null : productAvator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", shopId=").append(shopId);
        sb.append(", tagId=").append(tagId);
        sb.append(", productTotal=").append(productTotal);
        sb.append(", productName=").append(productName);
        sb.append(", productType=").append(productType);
        sb.append(", productDesc=").append(productDesc);
        sb.append(", status=").append(status);
        sb.append(", productAvator=").append(productAvator);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}