package cn.armylife.common.Domain;

import java.io.Serializable;

public class Vip implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.vip_id
     *
     * @mbggenerated
     */
    private Long vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.group_number
     *
     * @mbggenerated
     */
    private Integer groupNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.creat_time
     *
     * @mbggenerated
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.vip_id
     *
     * @return the value of vip.vip_id
     *
     * @mbggenerated
     */
    public Long getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.vip_id
     *
     * @param vipId the value for vip.vip_id
     *
     * @mbggenerated
     */
    public void setVipId(Long vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.user_id
     *
     * @return the value of vip.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.user_id
     *
     * @param userId the value for vip.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.group_number
     *
     * @return the value of vip.group_number
     *
     * @mbggenerated
     */
    public Integer getGroupNumber() {
        return groupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.group_number
     *
     * @param groupNumber the value for vip.group_number
     *
     * @mbggenerated
     */
    public void setGroupNumber(Integer groupNumber) {
        this.groupNumber = groupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.user_name
     *
     * @return the value of vip.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.user_name
     *
     * @param userName the value for vip.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.creat_time
     *
     * @return the value of vip.creat_time
     *
     * @mbggenerated
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.creat_time
     *
     * @param creatTime the value for vip.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.number
     *
     * @return the value of vip.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.number
     *
     * @param number the value for vip.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vipId=").append(vipId);
        sb.append(", userId=").append(userId);
        sb.append(", groupNumber=").append(groupNumber);
        sb.append(", userName=").append(userName);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", number=").append(number);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}