package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Admin;
import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    List<Admin> selectAll();

    /**
     * 登录
     * @return
     */
    Admin loginAdmin(Admin admin);
}