package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.AfterOrderDetail;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AfterOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_order_detail
     *
     * @mbggenerated
     */
    int insert(AfterOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_order_detail
     *
     * @mbggenerated
     */
    List<AfterOrderDetail> selectAll();
}