package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.DeliveryOrder;

import java.util.List;

public interface DeliveryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated
     */
    int insert(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated
     */
    List<DeliveryOrder> selectAll();
}