package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Hairvip;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface HairvipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    int insert(Hairvip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    List<Hairvip> selectAll();
}