package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.MallProductsDetail;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MallProductsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_products_detail
     *
     * @mbggenerated
     */
    int insert(MallProductsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_products_detail
     *
     * @mbggenerated
     */
    List<MallProductsDetail> selectAll();
}