package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.MallProductsPicture;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MallProductsPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_products_picture
     *
     * @mbggenerated
     */
    int insert(MallProductsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_products_picture
     *
     * @mbggenerated
     */
    List<MallProductsPicture> selectAll();
}