package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Member;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    Page<Member> selectAll();

    /**
     * 查询用户总数
     * @return
     */
    Integer numberForUsers();

    /**
     * 查询时间段数据
     * @param time
     * @return
     */
    Integer weekNumForUsers(String time);
}