package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Payments;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    int insert(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    List<Payments> selectAll();
}