package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.PointsMallProducts;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PointsMallProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    int insert(PointsMallProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    Page<PointsMallProducts> selectAll();

    /**
     * 更新商品数据
     * @param pointsMallProducts
     * @return
     */
    int updateProduct(PointsMallProducts pointsMallProducts);

    /**
     * 通过ID查询商品
     * @param pointsMallProductsId
     * @return
     */
    PointsMallProducts selectForId(Long pointsMallProductsId);
}