package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.PointsExchangeRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PointsExchangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    int insert(PointsExchangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    List<PointsExchangeRecord> selectAll();
}