package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.PointsMallProducts;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PointsMallProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    int insert(PointsMallProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    Page<PointsMallProducts> selectAll();
}