package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.PointsExchangeRecord;

import java.util.List;

public interface PointsExchangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    int insert(PointsExchangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    List<PointsExchangeRecord> selectAll();
}