package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.ProductDetail;

import java.util.List;

public interface ProductDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbggenerated
     */
    int insert(ProductDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail
     *
     * @mbggenerated
     */
    List<ProductDetail> selectAll();
}