package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.ShopOrder;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ShopOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated
     */
    int insert(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated
     */
    Page<ShopOrder> selectAll();

    /**
     * 查询当日总收入
     * @param time
     * @return
     */
    Integer incomeToDay(String time);
}