package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Transactions;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbggenerated
     */
    int insert(Transactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbggenerated
     */
    List<Transactions> selectAll();
}