package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Transactions;

import java.util.List;

public interface TransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbggenerated
     */
    int insert(Transactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbggenerated
     */
    List<Transactions> selectAll();
}