package cn.armylife.admin.mapper;

import cn.armylife.admin.domain.Vip;

import java.util.List;

public interface VipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbggenerated
     */
    int insert(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbggenerated
     */
    List<Vip> selectAll();
}