package cn.armylife.union.domain;

import java.io.Serializable;

public class Favorites implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.type
     *
     * @mbggenerated
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.favorites_id
     *
     * @mbggenerated
     */
    private Long favoritesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites.favorites_title
     *
     * @mbggenerated
     */
    private String favoritesTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table favorites
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.type
     *
     * @return the value of favorites.type
     *
     * @mbggenerated
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.type
     *
     * @param type the value for favorites.type
     *
     * @mbggenerated
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.favorites_id
     *
     * @return the value of favorites.favorites_id
     *
     * @mbggenerated
     */
    public Long getFavoritesId() {
        return favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.favorites_id
     *
     * @param favoritesId the value for favorites.favorites_id
     *
     * @mbggenerated
     */
    public void setFavoritesId(Long favoritesId) {
        this.favoritesId = favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites.favorites_title
     *
     * @return the value of favorites.favorites_title
     *
     * @mbggenerated
     */
    public String getFavoritesTitle() {
        return favoritesTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites.favorites_title
     *
     * @param favoritesTitle the value for favorites.favorites_title
     *
     * @mbggenerated
     */
    public void setFavoritesTitle(String favoritesTitle) {
        this.favoritesTitle = favoritesTitle == null ? null : favoritesTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", type=").append(type);
        sb.append(", favoritesId=").append(favoritesId);
        sb.append(", favoritesTitle=").append(favoritesTitle);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}