package cn.armylife.union.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class FavoritesItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.num_iid
     *
     * @mbggenerated
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.pict_url
     *
     * @mbggenerated
     */
    private String pictUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.small_images
     *
     * @mbggenerated
     */
    private List<String> smallImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.reserve_price
     *
     * @mbggenerated
     */
    private String reservePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.zk_final_price
     *
     * @mbggenerated
     */
    private String zkFinalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.user_type
     *
     * @mbggenerated
     */
    private BigDecimal userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.provcity
     *
     * @mbggenerated
     */
    private String provcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.item_url
     *
     * @mbggenerated
     */
    private String itemUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.click_url
     *
     * @mbggenerated
     */
    private String clickUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.nick
     *
     * @mbggenerated
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.seller_id
     *
     * @mbggenerated
     */
    private BigDecimal sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.volume
     *
     * @mbggenerated
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.tk_rate
     *
     * @mbggenerated
     */
    private String tkRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.zk_final_price_wap
     *
     * @mbggenerated
     */
    private String zkFinalPriceWap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.shop_title
     *
     * @mbggenerated
     */
    private String shopTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.event_start_time
     *
     * @mbggenerated
     */
    private Date eventStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.event_end_time
     *
     * @mbggenerated
     */
    private Date eventEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.type
     *
     * @mbggenerated
     */
    private BigDecimal type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.status
     *
     * @mbggenerated
     */
    private BigDecimal status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.category
     *
     * @mbggenerated
     */
    private BigDecimal category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.coupon_click_url
     *
     * @mbggenerated
     */
    private String couponClickUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.coupon_end_time
     *
     * @mbggenerated
     */
    private String couponEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.coupon_info
     *
     * @mbggenerated
     */
    private String couponInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.coupon_start_time
     *
     * @mbggenerated
     */
    private String couponStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.coupon_total_count
     *
     * @mbggenerated
     */
    private BigDecimal couponTotalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorites_item.coupon_remain_count
     *
     * @mbggenerated
     */
    private BigDecimal couponRemainCount;

    private BigDecimal ocuponAmount;

    public BigDecimal getOcuponAmount() {
        return ocuponAmount;
    }

    public void setOcuponAmount(BigDecimal ocuponAmount) {
        this.ocuponAmount = ocuponAmount;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table favorites_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.num_iid
     *
     * @return the value of favorites_item.num_iid
     *
     * @mbggenerated
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.num_iid
     *
     * @param numIid the value for favorites_item.num_iid
     *
     * @mbggenerated
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.title
     *
     * @return the value of favorites_item.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.title
     *
     * @param title the value for favorites_item.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.pict_url
     *
     * @return the value of favorites_item.pict_url
     *
     * @mbggenerated
     */
    public String getPictUrl() {
        return pictUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.pict_url
     *
     * @param pictUrl the value for favorites_item.pict_url
     *
     * @mbggenerated
     */
    public void setPictUrl(String pictUrl) {
        this.pictUrl = pictUrl == null ? null : pictUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.small_images
     *
     * @return the value of favorites_item.small_images
     *
     * @mbggenerated
     */
    public List<String> getSmallImages() {
        return smallImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.small_images
     *
     * @param smallImages the value for favorites_item.small_images
     *
     * @mbggenerated
     */
    public void setSmallImages(List<String> smallImages) {
        this.smallImages = smallImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.reserve_price
     *
     * @return the value of favorites_item.reserve_price
     *
     * @mbggenerated
     */
    public String getReservePrice() {
        return reservePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.reserve_price
     *
     * @param reservePrice the value for favorites_item.reserve_price
     *
     * @mbggenerated
     */
    public void setReservePrice(String reservePrice) {
        this.reservePrice = reservePrice == null ? null : reservePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.zk_final_price
     *
     * @return the value of favorites_item.zk_final_price
     *
     * @mbggenerated
     */
    public String getZkFinalPrice() {
        return zkFinalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.zk_final_price
     *
     * @param zkFinalPrice the value for favorites_item.zk_final_price
     *
     * @mbggenerated
     */
    public void setZkFinalPrice(String zkFinalPrice) {
        this.zkFinalPrice = zkFinalPrice == null ? null : zkFinalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.user_type
     *
     * @return the value of favorites_item.user_type
     *
     * @mbggenerated
     */
    public BigDecimal getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.user_type
     *
     * @param userType the value for favorites_item.user_type
     *
     * @mbggenerated
     */
    public void setUserType(BigDecimal userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.provcity
     *
     * @return the value of favorites_item.provcity
     *
     * @mbggenerated
     */
    public String getProvcity() {
        return provcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.provcity
     *
     * @param provcity the value for favorites_item.provcity
     *
     * @mbggenerated
     */
    public void setProvcity(String provcity) {
        this.provcity = provcity == null ? null : provcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.item_url
     *
     * @return the value of favorites_item.item_url
     *
     * @mbggenerated
     */
    public String getItemUrl() {
        return itemUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.item_url
     *
     * @param itemUrl the value for favorites_item.item_url
     *
     * @mbggenerated
     */
    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl == null ? null : itemUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.click_url
     *
     * @return the value of favorites_item.click_url
     *
     * @mbggenerated
     */
    public String getClickUrl() {
        return clickUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.click_url
     *
     * @param clickUrl the value for favorites_item.click_url
     *
     * @mbggenerated
     */
    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl == null ? null : clickUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.nick
     *
     * @return the value of favorites_item.nick
     *
     * @mbggenerated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.nick
     *
     * @param nick the value for favorites_item.nick
     *
     * @mbggenerated
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.seller_id
     *
     * @return the value of favorites_item.seller_id
     *
     * @mbggenerated
     */
    public BigDecimal getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.seller_id
     *
     * @param sellerId the value for favorites_item.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(BigDecimal sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.volume
     *
     * @return the value of favorites_item.volume
     *
     * @mbggenerated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.volume
     *
     * @param volume the value for favorites_item.volume
     *
     * @mbggenerated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.tk_rate
     *
     * @return the value of favorites_item.tk_rate
     *
     * @mbggenerated
     */
    public String getTkRate() {
        return tkRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.tk_rate
     *
     * @param tkRate the value for favorites_item.tk_rate
     *
     * @mbggenerated
     */
    public void setTkRate(String tkRate) {
        this.tkRate = tkRate == null ? null : tkRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.zk_final_price_wap
     *
     * @return the value of favorites_item.zk_final_price_wap
     *
     * @mbggenerated
     */
    public String getZkFinalPriceWap() {
        return zkFinalPriceWap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.zk_final_price_wap
     *
     * @param zkFinalPriceWap the value for favorites_item.zk_final_price_wap
     *
     * @mbggenerated
     */
    public void setZkFinalPriceWap(String zkFinalPriceWap) {
        this.zkFinalPriceWap = zkFinalPriceWap == null ? null : zkFinalPriceWap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.shop_title
     *
     * @return the value of favorites_item.shop_title
     *
     * @mbggenerated
     */
    public String getShopTitle() {
        return shopTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.shop_title
     *
     * @param shopTitle the value for favorites_item.shop_title
     *
     * @mbggenerated
     */
    public void setShopTitle(String shopTitle) {
        this.shopTitle = shopTitle == null ? null : shopTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.event_start_time
     *
     * @return the value of favorites_item.event_start_time
     *
     * @mbggenerated
     */
    public Date getEventStartTime() {
        return eventStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.event_start_time
     *
     * @param eventStartTime the value for favorites_item.event_start_time
     *
     * @mbggenerated
     */
    public void setEventStartTime(Date eventStartTime) {
        this.eventStartTime = eventStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.event_end_time
     *
     * @return the value of favorites_item.event_end_time
     *
     * @mbggenerated
     */
    public Date getEventEndTime() {
        return eventEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.event_end_time
     *
     * @param eventEndTime the value for favorites_item.event_end_time
     *
     * @mbggenerated
     */
    public void setEventEndTime(Date eventEndTime) {
        this.eventEndTime = eventEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.type
     *
     * @return the value of favorites_item.type
     *
     * @mbggenerated
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.type
     *
     * @param type the value for favorites_item.type
     *
     * @mbggenerated
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.status
     *
     * @return the value of favorites_item.status
     *
     * @mbggenerated
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.status
     *
     * @param status the value for favorites_item.status
     *
     * @mbggenerated
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.category
     *
     * @return the value of favorites_item.category
     *
     * @mbggenerated
     */
    public BigDecimal getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.category
     *
     * @param category the value for favorites_item.category
     *
     * @mbggenerated
     */
    public void setCategory(BigDecimal category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.coupon_click_url
     *
     * @return the value of favorites_item.coupon_click_url
     *
     * @mbggenerated
     */
    public String getCouponClickUrl() {
        return couponClickUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.coupon_click_url
     *
     * @param couponClickUrl the value for favorites_item.coupon_click_url
     *
     * @mbggenerated
     */
    public void setCouponClickUrl(String couponClickUrl) {
        this.couponClickUrl = couponClickUrl == null ? null : couponClickUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.coupon_end_time
     *
     * @return the value of favorites_item.coupon_end_time
     *
     * @mbggenerated
     */
    public String getCouponEndTime() {
        return couponEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.coupon_end_time
     *
     * @param couponEndTime the value for favorites_item.coupon_end_time
     *
     * @mbggenerated
     */
    public void setCouponEndTime(String couponEndTime) {
        this.couponEndTime = couponEndTime == null ? null : couponEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.coupon_info
     *
     * @return the value of favorites_item.coupon_info
     *
     * @mbggenerated
     */
    public String getCouponInfo() {
        return couponInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.coupon_info
     *
     * @param couponInfo the value for favorites_item.coupon_info
     *
     * @mbggenerated
     */
    public void setCouponInfo(String couponInfo) {
        this.couponInfo = couponInfo == null ? null : couponInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.coupon_start_time
     *
     * @return the value of favorites_item.coupon_start_time
     *
     * @mbggenerated
     */
    public String getCouponStartTime() {
        return couponStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.coupon_start_time
     *
     * @param couponStartTime the value for favorites_item.coupon_start_time
     *
     * @mbggenerated
     */
    public void setCouponStartTime(String couponStartTime) {
        this.couponStartTime = couponStartTime == null ? null : couponStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.coupon_total_count
     *
     * @return the value of favorites_item.coupon_total_count
     *
     * @mbggenerated
     */
    public BigDecimal getCouponTotalCount() {
        return couponTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.coupon_total_count
     *
     * @param couponTotalCount the value for favorites_item.coupon_total_count
     *
     * @mbggenerated
     */
    public void setCouponTotalCount(BigDecimal couponTotalCount) {
        this.couponTotalCount = couponTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorites_item.coupon_remain_count
     *
     * @return the value of favorites_item.coupon_remain_count
     *
     * @mbggenerated
     */
    public BigDecimal getCouponRemainCount() {
        return couponRemainCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorites_item.coupon_remain_count
     *
     * @param couponRemainCount the value for favorites_item.coupon_remain_count
     *
     * @mbggenerated
     */
    public void setCouponRemainCount(BigDecimal couponRemainCount) {
        this.couponRemainCount = couponRemainCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", numIid=").append(numIid);
        sb.append(", title=").append(title);
        sb.append(", pictUrl=").append(pictUrl);
        sb.append(", smallImages=").append(smallImages);
        sb.append(", reservePrice=").append(reservePrice);
        sb.append(", zkFinalPrice=").append(zkFinalPrice);
        sb.append(", userType=").append(userType);
        sb.append(", provcity=").append(provcity);
        sb.append(", itemUrl=").append(itemUrl);
        sb.append(", clickUrl=").append(clickUrl);
        sb.append(", nick=").append(nick);
        sb.append(", sellerId=").append(sellerId);
        sb.append(", volume=").append(volume);
        sb.append(", tkRate=").append(tkRate);
        sb.append(", zkFinalPriceWap=").append(zkFinalPriceWap);
        sb.append(", shopTitle=").append(shopTitle);
        sb.append(", eventStartTime=").append(eventStartTime);
        sb.append(", eventEndTime=").append(eventEndTime);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", category=").append(category);
        sb.append(", couponClickUrl=").append(couponClickUrl);
        sb.append(", couponEndTime=").append(couponEndTime);
        sb.append(", couponInfo=").append(couponInfo);
        sb.append(", couponStartTime=").append(couponStartTime);
        sb.append(", couponTotalCount=").append(couponTotalCount);
        sb.append(", couponRemainCount=").append(couponRemainCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}