package cn.armylife.union.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class ItemInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.cat_name
     *
     * @mbggenerated
     */
    private String catName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.num_iid
     *
     * @mbggenerated
     */
    private BigDecimal numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.pict_url
     *
     * @mbggenerated
     */
    private String pictUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.small_images
     *
     * @mbggenerated
     */
    private BigDecimal smallImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.reserve_price
     *
     * @mbggenerated
     */
    private String reservePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.zk_final_price
     *
     * @mbggenerated
     */
    private String zkFinalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.user_type
     *
     * @mbggenerated
     */
    private Long userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.provcity
     *
     * @mbggenerated
     */
    private String provcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_url
     *
     * @mbggenerated
     */
    private String itemUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.seller_id
     *
     * @mbggenerated
     */
    private BigDecimal sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.volume
     *
     * @mbggenerated
     */
    private Long volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.nick
     *
     * @mbggenerated
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.cat_leaf_name
     *
     * @mbggenerated
     */
    private String catLeafName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.is_prepay
     *
     * @mbggenerated
     */
    private Boolean isPrepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.shop_dsr
     *
     * @mbggenerated
     */
    private BigDecimal shopDsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.ratesum
     *
     * @mbggenerated
     */
    private BigDecimal ratesum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.i_rfd_rate
     *
     * @mbggenerated
     */
    private Boolean iRfdRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.h_good_rate
     *
     * @mbggenerated
     */
    private Boolean hGoodRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.h_pay_rate30
     *
     * @mbggenerated
     */
    private Boolean hPayRate30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.free_shipment
     *
     * @mbggenerated
     */
    private Boolean freeShipment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.material_lib_type
     *
     * @mbggenerated
     */
    private String materialLibType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.presale_discount_fee_text
     *
     * @mbggenerated
     */
    private String presaleDiscountFeeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.presale_tail_end_time
     *
     * @mbggenerated
     */
    private BigDecimal presaleTailEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.presale_tail_start_time
     *
     * @mbggenerated
     */
    private BigDecimal presaleTailStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.presale_end_time
     *
     * @mbggenerated
     */
    private BigDecimal presaleEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.presale_start_time
     *
     * @mbggenerated
     */
    private BigDecimal presaleStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.presale_deposit
     *
     * @mbggenerated
     */
    private String presaleDeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.ju_play_end_time
     *
     * @mbggenerated
     */
    private BigDecimal juPlayEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.ju_play_start_time
     *
     * @mbggenerated
     */
    private BigDecimal juPlayStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.play_info
     *
     * @mbggenerated
     */
    private String playInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.tmall_play_activity_end_time
     *
     * @mbggenerated
     */
    private BigDecimal tmallPlayActivityEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.tmall_play_activity_start_time
     *
     * @mbggenerated
     */
    private BigDecimal tmallPlayActivityStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.cat_name
     *
     * @return the value of item_info.cat_name
     *
     * @mbggenerated
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.cat_name
     *
     * @param catName the value for item_info.cat_name
     *
     * @mbggenerated
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.num_iid
     *
     * @return the value of item_info.num_iid
     *
     * @mbggenerated
     */
    public BigDecimal getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.num_iid
     *
     * @param numIid the value for item_info.num_iid
     *
     * @mbggenerated
     */
    public void setNumIid(BigDecimal numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.title
     *
     * @return the value of item_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.title
     *
     * @param title the value for item_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.pict_url
     *
     * @return the value of item_info.pict_url
     *
     * @mbggenerated
     */
    public String getPictUrl() {
        return pictUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.pict_url
     *
     * @param pictUrl the value for item_info.pict_url
     *
     * @mbggenerated
     */
    public void setPictUrl(String pictUrl) {
        this.pictUrl = pictUrl == null ? null : pictUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.small_images
     *
     * @return the value of item_info.small_images
     *
     * @mbggenerated
     */
    public BigDecimal getSmallImages() {
        return smallImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.small_images
     *
     * @param smallImages the value for item_info.small_images
     *
     * @mbggenerated
     */
    public void setSmallImages(BigDecimal smallImages) {
        this.smallImages = smallImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.reserve_price
     *
     * @return the value of item_info.reserve_price
     *
     * @mbggenerated
     */
    public String getReservePrice() {
        return reservePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.reserve_price
     *
     * @param reservePrice the value for item_info.reserve_price
     *
     * @mbggenerated
     */
    public void setReservePrice(String reservePrice) {
        this.reservePrice = reservePrice == null ? null : reservePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.zk_final_price
     *
     * @return the value of item_info.zk_final_price
     *
     * @mbggenerated
     */
    public String getZkFinalPrice() {
        return zkFinalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.zk_final_price
     *
     * @param zkFinalPrice the value for item_info.zk_final_price
     *
     * @mbggenerated
     */
    public void setZkFinalPrice(String zkFinalPrice) {
        this.zkFinalPrice = zkFinalPrice == null ? null : zkFinalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.user_type
     *
     * @return the value of item_info.user_type
     *
     * @mbggenerated
     */
    public Long getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.user_type
     *
     * @param userType the value for item_info.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Long userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.provcity
     *
     * @return the value of item_info.provcity
     *
     * @mbggenerated
     */
    public String getProvcity() {
        return provcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.provcity
     *
     * @param provcity the value for item_info.provcity
     *
     * @mbggenerated
     */
    public void setProvcity(String provcity) {
        this.provcity = provcity == null ? null : provcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_url
     *
     * @return the value of item_info.item_url
     *
     * @mbggenerated
     */
    public String getItemUrl() {
        return itemUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_url
     *
     * @param itemUrl the value for item_info.item_url
     *
     * @mbggenerated
     */
    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl == null ? null : itemUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.seller_id
     *
     * @return the value of item_info.seller_id
     *
     * @mbggenerated
     */
    public BigDecimal getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.seller_id
     *
     * @param sellerId the value for item_info.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(BigDecimal sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.volume
     *
     * @return the value of item_info.volume
     *
     * @mbggenerated
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.volume
     *
     * @param volume the value for item_info.volume
     *
     * @mbggenerated
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.nick
     *
     * @return the value of item_info.nick
     *
     * @mbggenerated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.nick
     *
     * @param nick the value for item_info.nick
     *
     * @mbggenerated
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.cat_leaf_name
     *
     * @return the value of item_info.cat_leaf_name
     *
     * @mbggenerated
     */
    public String getCatLeafName() {
        return catLeafName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.cat_leaf_name
     *
     * @param catLeafName the value for item_info.cat_leaf_name
     *
     * @mbggenerated
     */
    public void setCatLeafName(String catLeafName) {
        this.catLeafName = catLeafName == null ? null : catLeafName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.is_prepay
     *
     * @return the value of item_info.is_prepay
     *
     * @mbggenerated
     */
    public Boolean getIsPrepay() {
        return isPrepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.is_prepay
     *
     * @param isPrepay the value for item_info.is_prepay
     *
     * @mbggenerated
     */
    public void setIsPrepay(Boolean isPrepay) {
        this.isPrepay = isPrepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.shop_dsr
     *
     * @return the value of item_info.shop_dsr
     *
     * @mbggenerated
     */
    public BigDecimal getShopDsr() {
        return shopDsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.shop_dsr
     *
     * @param shopDsr the value for item_info.shop_dsr
     *
     * @mbggenerated
     */
    public void setShopDsr(BigDecimal shopDsr) {
        this.shopDsr = shopDsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.ratesum
     *
     * @return the value of item_info.ratesum
     *
     * @mbggenerated
     */
    public BigDecimal getRatesum() {
        return ratesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.ratesum
     *
     * @param ratesum the value for item_info.ratesum
     *
     * @mbggenerated
     */
    public void setRatesum(BigDecimal ratesum) {
        this.ratesum = ratesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.i_rfd_rate
     *
     * @return the value of item_info.i_rfd_rate
     *
     * @mbggenerated
     */
    public Boolean getiRfdRate() {
        return iRfdRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.i_rfd_rate
     *
     * @param iRfdRate the value for item_info.i_rfd_rate
     *
     * @mbggenerated
     */
    public void setiRfdRate(Boolean iRfdRate) {
        this.iRfdRate = iRfdRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.h_good_rate
     *
     * @return the value of item_info.h_good_rate
     *
     * @mbggenerated
     */
    public Boolean gethGoodRate() {
        return hGoodRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.h_good_rate
     *
     * @param hGoodRate the value for item_info.h_good_rate
     *
     * @mbggenerated
     */
    public void sethGoodRate(Boolean hGoodRate) {
        this.hGoodRate = hGoodRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.h_pay_rate30
     *
     * @return the value of item_info.h_pay_rate30
     *
     * @mbggenerated
     */
    public Boolean gethPayRate30() {
        return hPayRate30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.h_pay_rate30
     *
     * @param hPayRate30 the value for item_info.h_pay_rate30
     *
     * @mbggenerated
     */
    public void sethPayRate30(Boolean hPayRate30) {
        this.hPayRate30 = hPayRate30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.free_shipment
     *
     * @return the value of item_info.free_shipment
     *
     * @mbggenerated
     */
    public Boolean getFreeShipment() {
        return freeShipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.free_shipment
     *
     * @param freeShipment the value for item_info.free_shipment
     *
     * @mbggenerated
     */
    public void setFreeShipment(Boolean freeShipment) {
        this.freeShipment = freeShipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.material_lib_type
     *
     * @return the value of item_info.material_lib_type
     *
     * @mbggenerated
     */
    public String getMaterialLibType() {
        return materialLibType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.material_lib_type
     *
     * @param materialLibType the value for item_info.material_lib_type
     *
     * @mbggenerated
     */
    public void setMaterialLibType(String materialLibType) {
        this.materialLibType = materialLibType == null ? null : materialLibType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.presale_discount_fee_text
     *
     * @return the value of item_info.presale_discount_fee_text
     *
     * @mbggenerated
     */
    public String getPresaleDiscountFeeText() {
        return presaleDiscountFeeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.presale_discount_fee_text
     *
     * @param presaleDiscountFeeText the value for item_info.presale_discount_fee_text
     *
     * @mbggenerated
     */
    public void setPresaleDiscountFeeText(String presaleDiscountFeeText) {
        this.presaleDiscountFeeText = presaleDiscountFeeText == null ? null : presaleDiscountFeeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.presale_tail_end_time
     *
     * @return the value of item_info.presale_tail_end_time
     *
     * @mbggenerated
     */
    public BigDecimal getPresaleTailEndTime() {
        return presaleTailEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.presale_tail_end_time
     *
     * @param presaleTailEndTime the value for item_info.presale_tail_end_time
     *
     * @mbggenerated
     */
    public void setPresaleTailEndTime(BigDecimal presaleTailEndTime) {
        this.presaleTailEndTime = presaleTailEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.presale_tail_start_time
     *
     * @return the value of item_info.presale_tail_start_time
     *
     * @mbggenerated
     */
    public BigDecimal getPresaleTailStartTime() {
        return presaleTailStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.presale_tail_start_time
     *
     * @param presaleTailStartTime the value for item_info.presale_tail_start_time
     *
     * @mbggenerated
     */
    public void setPresaleTailStartTime(BigDecimal presaleTailStartTime) {
        this.presaleTailStartTime = presaleTailStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.presale_end_time
     *
     * @return the value of item_info.presale_end_time
     *
     * @mbggenerated
     */
    public BigDecimal getPresaleEndTime() {
        return presaleEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.presale_end_time
     *
     * @param presaleEndTime the value for item_info.presale_end_time
     *
     * @mbggenerated
     */
    public void setPresaleEndTime(BigDecimal presaleEndTime) {
        this.presaleEndTime = presaleEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.presale_start_time
     *
     * @return the value of item_info.presale_start_time
     *
     * @mbggenerated
     */
    public BigDecimal getPresaleStartTime() {
        return presaleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.presale_start_time
     *
     * @param presaleStartTime the value for item_info.presale_start_time
     *
     * @mbggenerated
     */
    public void setPresaleStartTime(BigDecimal presaleStartTime) {
        this.presaleStartTime = presaleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.presale_deposit
     *
     * @return the value of item_info.presale_deposit
     *
     * @mbggenerated
     */
    public String getPresaleDeposit() {
        return presaleDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.presale_deposit
     *
     * @param presaleDeposit the value for item_info.presale_deposit
     *
     * @mbggenerated
     */
    public void setPresaleDeposit(String presaleDeposit) {
        this.presaleDeposit = presaleDeposit == null ? null : presaleDeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.ju_play_end_time
     *
     * @return the value of item_info.ju_play_end_time
     *
     * @mbggenerated
     */
    public BigDecimal getJuPlayEndTime() {
        return juPlayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.ju_play_end_time
     *
     * @param juPlayEndTime the value for item_info.ju_play_end_time
     *
     * @mbggenerated
     */
    public void setJuPlayEndTime(BigDecimal juPlayEndTime) {
        this.juPlayEndTime = juPlayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.ju_play_start_time
     *
     * @return the value of item_info.ju_play_start_time
     *
     * @mbggenerated
     */
    public BigDecimal getJuPlayStartTime() {
        return juPlayStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.ju_play_start_time
     *
     * @param juPlayStartTime the value for item_info.ju_play_start_time
     *
     * @mbggenerated
     */
    public void setJuPlayStartTime(BigDecimal juPlayStartTime) {
        this.juPlayStartTime = juPlayStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.play_info
     *
     * @return the value of item_info.play_info
     *
     * @mbggenerated
     */
    public String getPlayInfo() {
        return playInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.play_info
     *
     * @param playInfo the value for item_info.play_info
     *
     * @mbggenerated
     */
    public void setPlayInfo(String playInfo) {
        this.playInfo = playInfo == null ? null : playInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.tmall_play_activity_end_time
     *
     * @return the value of item_info.tmall_play_activity_end_time
     *
     * @mbggenerated
     */
    public BigDecimal getTmallPlayActivityEndTime() {
        return tmallPlayActivityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.tmall_play_activity_end_time
     *
     * @param tmallPlayActivityEndTime the value for item_info.tmall_play_activity_end_time
     *
     * @mbggenerated
     */
    public void setTmallPlayActivityEndTime(BigDecimal tmallPlayActivityEndTime) {
        this.tmallPlayActivityEndTime = tmallPlayActivityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.tmall_play_activity_start_time
     *
     * @return the value of item_info.tmall_play_activity_start_time
     *
     * @mbggenerated
     */
    public BigDecimal getTmallPlayActivityStartTime() {
        return tmallPlayActivityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.tmall_play_activity_start_time
     *
     * @param tmallPlayActivityStartTime the value for item_info.tmall_play_activity_start_time
     *
     * @mbggenerated
     */
    public void setTmallPlayActivityStartTime(BigDecimal tmallPlayActivityStartTime) {
        this.tmallPlayActivityStartTime = tmallPlayActivityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", catName=").append(catName);
        sb.append(", numIid=").append(numIid);
        sb.append(", title=").append(title);
        sb.append(", pictUrl=").append(pictUrl);
        sb.append(", smallImages=").append(smallImages);
        sb.append(", reservePrice=").append(reservePrice);
        sb.append(", zkFinalPrice=").append(zkFinalPrice);
        sb.append(", userType=").append(userType);
        sb.append(", provcity=").append(provcity);
        sb.append(", itemUrl=").append(itemUrl);
        sb.append(", sellerId=").append(sellerId);
        sb.append(", volume=").append(volume);
        sb.append(", nick=").append(nick);
        sb.append(", catLeafName=").append(catLeafName);
        sb.append(", isPrepay=").append(isPrepay);
        sb.append(", shopDsr=").append(shopDsr);
        sb.append(", ratesum=").append(ratesum);
        sb.append(", iRfdRate=").append(iRfdRate);
        sb.append(", hGoodRate=").append(hGoodRate);
        sb.append(", hPayRate30=").append(hPayRate30);
        sb.append(", freeShipment=").append(freeShipment);
        sb.append(", materialLibType=").append(materialLibType);
        sb.append(", presaleDiscountFeeText=").append(presaleDiscountFeeText);
        sb.append(", presaleTailEndTime=").append(presaleTailEndTime);
        sb.append(", presaleTailStartTime=").append(presaleTailStartTime);
        sb.append(", presaleEndTime=").append(presaleEndTime);
        sb.append(", presaleStartTime=").append(presaleStartTime);
        sb.append(", presaleDeposit=").append(presaleDeposit);
        sb.append(", juPlayEndTime=").append(juPlayEndTime);
        sb.append(", juPlayStartTime=").append(juPlayStartTime);
        sb.append(", playInfo=").append(playInfo);
        sb.append(", tmallPlayActivityEndTime=").append(tmallPlayActivityEndTime);
        sb.append(", tmallPlayActivityStartTime=").append(tmallPlayActivityStartTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}