package cn.armylife.union.domain;

import java.io.Serializable;

public class SmallImages implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_images.small_images
     *
     * @mbggenerated
     */
    private String smallImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_images.num_iid
     *
     * @mbggenerated
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_images.small_images_id
     *
     * @mbggenerated
     */
    private Long smallImagesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table small_images
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_images.small_images
     *
     * @return the value of small_images.small_images
     *
     * @mbggenerated
     */
    public String getSmallImages() {
        return smallImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_images.small_images
     *
     * @param smallImages the value for small_images.small_images
     *
     * @mbggenerated
     */
    public void setSmallImages(String smallImages) {
        this.smallImages = smallImages == null ? null : smallImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_images.num_iid
     *
     * @return the value of small_images.num_iid
     *
     * @mbggenerated
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_images.num_iid
     *
     * @param numIid the value for small_images.num_iid
     *
     * @mbggenerated
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_images.small_images_id
     *
     * @return the value of small_images.small_images_id
     *
     * @mbggenerated
     */
    public Long getSmallImagesId() {
        return smallImagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_images.small_images_id
     *
     * @param smallImagesId the value for small_images.small_images_id
     *
     * @mbggenerated
     */
    public void setSmallImagesId(Long smallImagesId) {
        this.smallImagesId = smallImagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_images
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", smallImages=").append(smallImages);
        sb.append(", numIid=").append(numIid);
        sb.append(", smallImagesId=").append(smallImagesId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}