package cn.armylife.union.mapper;

import com.github.pagehelper.Page;
import com.taobao.api.domain.UatmTbkItem;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FavoritesItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites_item
     *
     * @mbggenerated
     */
    int insert(UatmTbkItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorites_item
     *
     * @mbggenerated
     */
    Page<UatmTbkItem> selectAll();

}