package cn.armylife.union.mapper;

import cn.armylife.union.domain.ItemInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated
     */
    int insert(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated
     */
    List<ItemInfo> selectAll();
}