package cn.armylife.market.Mapper;

import cn.armylife.common.Domain.AfterOrderDetail;

import java.util.List;

public interface AfterOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_order_detail
     *
     * @mbggenerated
     */
    int insert(AfterOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_order_detail
     *
     * @mbggenerated
     */
    List<AfterOrderDetail> selectAll();
}