package cn.armylife.market.Mapper;

import cn.armylife.common.Domain.Hairvip;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface HairvipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    int insert(Hairvip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    List<Hairvip> selectAll();

    /**
     * 查找理发店会员
     * @param memberId
     * @return
     */
    Hairvip selectHairvip(Long memberId);

    /**
     * 续费会员
     * @param hairvip
     * @return
     */
    int updateHair(Hairvip hairvip);
}

