package cn.armylife.market.mapper;

import cn.armylife.common.domain.Hairvip;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface HairvipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    int insert(Hairvip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hairvip
     *
     * @mbggenerated
     */
    List<Hairvip> selectAll();

    List<Hairvip> searchAll();

    /**
     * 查找理发店会员
     * @param memberId
     * @return
     */
    Hairvip selectHairvip(Long memberId);

    /**
     * 续费会员
     * @param hairvip
     * @return
     */
    int updateHair(Hairvip hairvip);

    /**
     * 通过会员名查询用户信息
     * @param vipName
     * @return
     */
    List<Hairvip> searchHairVip(String vipName);
}

