package cn.armylife.market.Mapper;

import cn.armylife.common.Domain.Payments;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface PaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer paymentsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    int insert(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    Payments selectByPrimaryKey(Integer paymentsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    List<Payments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Payments record);
}