package cn.armylife.market.mapper;

import cn.armylife.common.domain.Product;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    List<Product> selectProductForShop(Product product);

    int offShelves(Long productId);

    Product selectProductNews(String product);

    int updateProducts(Product product);

    /**
     * 当日商品统计
     * @param shopId
     * @return
     */
    List<Product> rankForProduct(Long shopId);

    /**
     * 查询商品信息
     * @param productId
     * @return
     */
    Product getProduct(Long productId);
}