package cn.armylife.market.Mapper;

import cn.armylife.common.Domain.ShopTag;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ShopTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tag
     *
     * @mbggenerated
     */
    int insert(ShopTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tag
     *
     * @mbggenerated
     */
    List<ShopTag> selectAll();



    /**
     * 查询店铺商品分类
     * @param shopId
     * @return
     */
    List<ShopTag> FindShopTag(Long shopId);

    /**
     * 查询店铺所有商品
     * @param shopId
     * @return
     */
    List<ShopTag> selectShopProduct(Long shopId);
}