package cn.armylife.market.mapper;

import cn.armylife.common.domain.ShopTag;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ShopTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tag
     *
     * @mbggenerated
     */
    int insert(ShopTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_tag
     *
     * @mbggenerated
     */
    List<ShopTag> selectAll();



    /**
     * 查询店铺商品分类
     * @param shopId
     * @return
     */
    List<ShopTag> FindShopTag(Long shopId);

    /**
     * 查询店铺所有商品
     * @param shopId
     * @return
     */
    List<ShopTag> selectShopProduct(Long shopId);

    /**
     * 删除商户分类
     * @param shopTagId
     * @return
     */
    int removeTag(Long shopTagId);

    /**
     * 更新tagId
     * @param shopTagId
     * @param tagId
     * @return
     */
    int updateTag(Long shopTagId,int tagId);

    /**
     * 更新shop_tag的tag_name名
     * @param shopTag
     * @return
     */
    int updateTagName(ShopTag shopTag);
}