package cn.armylife.market.mapper;

import cn.armylife.common.domain.Vip;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbggenerated
     */
    int insert(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbggenerated
     */
    List<Vip> selectAll();

    /**
     * 查询认领会员
     * @param userName
     * @param groupNumber
     * @return
     */
    Vip FindVip(@Param("userName") String userName,@Param("groupNumber") String groupNumber);

    /**
     * 删除未认领会员
     * @param vipId
     * @return
     */
    int removeVip(Long vipId);
}