package cn.armylife.integralmall.Mapper;

import cn.armylife.common.Domain.IntegralRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IntegralRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_record
     *
     * @mbggenerated
     */
    int insert(IntegralRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_record
     *
     * @mbggenerated
     */
    List<IntegralRecord> selectAll();
}