package cn.armylife.integralmall.Mapper;

import cn.armylife.common.Domain.IntegralUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IntegralUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_user
     *
     * @mbggenerated
     */
    int insert(IntegralUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_user
     *
     * @mbggenerated
     */
    List<IntegralUser> selectAll();

    /**
     * 变更积分
     * @param integralUser
     * @return
     */
    int integralChange(IntegralUser integralUser);

    /**
     * 通过用户Id查找用户积分
     * @param userId
     * @return
     */
    IntegralUser findUserIntegral(Long userId);
}