package cn.armylife.integralmall.mapper;

import cn.armylife.common.domain.PointsMallProducts;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PointsMallProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    int insert(PointsMallProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_mall_products
     *
     * @mbggenerated
     */
    List<PointsMallProducts> selectAll();

    /**
     * 通过积分商品Id获取积分商品信息
     * @param pointsMallProductsId
     * @return
     */
    PointsMallProducts findMallProducts(Long pointsMallProductsId);

    /**
     * 通过分区Id查看商品
     * @param respectiveArea
     * @return
     */
    Page<PointsMallProducts> findProductForArea(Long respectiveArea);
}