package cn.armylife.integralmall.Mapper;

import cn.armylife.common.Domain.PointsExchangeRecord;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PointsExchangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    int insert(PointsExchangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_exchange_record
     *
     * @mbggenerated
     */
    List<PointsExchangeRecord> selectAll();

    /**
     * 查询兑换记录
     * @param userId
     * @return
     */
    Page<PointsExchangeRecord> findExchangeRecord(Long userId);

    /**
     * 通过Id查询兑换记录
     * @param pointsExchangeRecordId
     * @return
     */
    PointsExchangeRecord findExchangeRecordForId(Long pointsExchangeRecordId);
}