package cn.armylife.admin.serviceimpl;

import cn.armylife.admin.domain.Admin;
import cn.armylife.admin.domain.Member;
import cn.armylife.admin.domain.ShopOrder;
import cn.armylife.admin.mapper.AdminMapper;
import cn.armylife.admin.mapper.MemberMapper;
import cn.armylife.admin.mapper.ShopOrderMapper;
import cn.armylife.admin.service.AdminService;
import com.github.pagehelper.Page;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class AdminServiceimpl implements AdminService {
    @Autowired
    MemberMapper memberMapper;

    @Autowired
    ShopOrderMapper shopOrderMapper;

    @Autowired
    AdminMapper adminMapper;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    @Override
    public Page<Member> userSelectAll(){
        return memberMapper.selectAll();
    };

    /**
     * 查询用户总数
     * @return
     */
    @Override
    public Integer numberForUsers(){
        return memberMapper.numberForUsers();
    };


    /**
     *查询当日总收入
     * @param time
     * @return
     */
    @Override
    public Integer incomeToDay(String time){
        return shopOrderMapper.incomeToDay(time);
    };

    /**
     * 查询时间段人数
     * @param time
     * @return
     */
    @Override
    public Integer weekNumForUsers(String time){
        return memberMapper.weekNumForUsers(time);
    };

    /**
     * 全部订单
     * @return
     */
    @Override
    public Page<ShopOrder> orderSelectAll(){
        return shopOrderMapper.selectAll();
    };

    /**
     * 登录
     * @return
     */
    @Override
    public Admin loginAdmin(Admin admin){
        return adminMapper.loginAdmin(admin);
    };

}
