package cn.armylife.payments.Mapper;

import cn.armylife.common.Domain.Transactions;

import java.util.List;

public interface TransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbggenerated
     */
    int insert(Transactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbggenerated
     */
    List<Transactions> selectAll();
}